#pragma config(StandardModel, "VEX IQ Clawbot")
#pragma config(RenamedStdModelSensor, port3, lineDetector)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
 This program instructs the robot to not move until it is placed over top of a "dark" area, effectively
 waiting while it sees a dark value. This example could be used for turning off a
 flashlight to start your robot.

 Note: Lighting conditions change from place to place, so the value '600' may need to be changed
       to better suit your environment. Grayscale Values can range from 0 to 2000 (possibly even higher)

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 5       				lineDetector       	VEX IQ Color		      			Color Detector (Grayscale Mode)
------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while(SensorValue(lineDetector) > 600) // While the Color sensor in 'grayscale' mode reads a value greater than 600
	{
		// Do nothing because we see "light"
	}

	setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	sleep(2000);										//Wait for 2 seconds before continuing on in the program.
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
