#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)//remember to enable external motor/servo controllers under Robot/Platform Type
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//                  TETRIX+NXT Encoder - nMotorEncoder Example

// The program below demonstrates how to use the nMotorEndocer function
// There are three steps to using the function
//    1. Zero out the LEGO encoder using "nMotorEncoder(motorX) = 0"   Lines 17 and 18.
//    2. Place the function into a conditional statement like a while loop.  Line 20
//    3. Turn the motors off. Lines 26 and 27.

task main()
{

  nMotorEncoder[motorC] = 0;  //clear the LEGO encoders in motors B and C
  nMotorEncoder[motorB] = 0;

  while (nMotorEncoder[motorB] < 1440) //while the encoder wheel turns one revolution
  {
    motor[motorE] = 30; //turn both TETRIX motors on at 30 percent power
    motor[motorD] = 30;
  }

  motor[motorE] = 0; //turn both TETRIX motors off
  motor[motorD] = 0;

  wait1Msec(3000); // wait 3 seconds to see feedback from the debugger screens
                    // open the "NXT Devices" window to see the distance the encoder
                    //spins. The robot will coast a little bit.
}
