#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Do-While Loop

This program uses a "do-while" loop to instruct your robot to traverse a square 5 times by
repeating moving forward and turning behaviors 20 times. There is a two second pause at the
beginning of the program.

When using "do-while" loops, the code between its braces is always run at least once, since the
condition is not checked until after it is run.

The integer variable 'i' is needed to keep track of the number of times that the "do-while" loop has run.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          NXT Motor             Right side motor
Motor Port 3        leftMotor           NXT Motor             Left side motor

*To run this sample program on Swervebot, be sure to Reverse Motor Port 3 in the Motors and Sensors
 Setup, and to make sure that Motor Port 2 is NOT Reversed.
----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						          // Robot waits for 2000 milliseconds before executing program

	int i = 0;									          // Declares integer variable 'i' and initializes it to 0

	do	// Using "do" guarantees the code will be run at least once since the condition is checked after each iteration, not before
	{

		// Move forward at half power for 2 seconds
		motor[rightMotor] = 50;			        // Motor on motorB is run at half (50) power forward
		motor[leftMotor]  = 50;			        // Motor on motorC is run at half (50) power forward
		wait1Msec(2000);				            // Robot runs previous code for 2000 milliseconds before moving on

		// Turn Left at half power for 0.5 seconds
		motor[rightMotor] = 50;     	      // Motor on motorB is run at half (50) power forward
		motor[leftMotor]  = -50;    	      // Motor on motorC is run at half (-50) power reverse
		wait1Msec(500);        	            // Robot runs previous code for 500 milliseconds before moving on

		i++;										            // increment i by 1 (same as "i = i + 1")

	}
	while(i < 20);	// This do-while() loop repeats the code above while 'i' is less than 20

}														            // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
