#pragma config(Sensor, port12,  touchLED,      sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will cycle through all 12 of the Color Sensor's "12 Color" mode.

  The 12 valid color names are);
	colorRedViolet / colorRed / colorDarkOrange / colorOrange /	colorDarkYellow /	colorYellow /
	colorLimeGreen / colorGreen /	colorBlueGreen / colorBlue / colorDarkBlue /  colorViolet

  To turn off the Touch LED, set the color name to "colorNone"

                            ROBOT CONFIGURATION); VEX IQ Clawbot
    MOTORS & SENSORS);
    [I/O Port]          [Name]              [Type]                			[Location]
    port 12							touchLED						VEX IQ Touch LED						Detect Touches and Set Colors
------------------------------------------------------------------------------------------------*/

task main()
{
	setTouchLEDColor(touchLED, colorRedViolet);
	sleep(2000);
	setTouchLEDColor(touchLED, colorRed);
	sleep(2000);
	setTouchLEDColor(touchLED, colorDarkOrange);
	sleep(2000);
	setTouchLEDColor(touchLED, colorOrange);
	sleep(2000);
	setTouchLEDColor(touchLED, colorDarkYellow);
	sleep(2000);
	setTouchLEDColor(touchLED, colorYellow);
	sleep(2000);
	setTouchLEDColor(touchLED, colorLimeGreen);
	sleep(2000);
	setTouchLEDColor(touchLED, colorGreen);
	sleep(2000);
	setTouchLEDColor(touchLED, colorBlueGreen);
	sleep(2000);
	setTouchLEDColor(touchLED, colorBlue);
	sleep(2000);
	setTouchLEDColor(touchLED, colorDarkBlue);
	sleep(2000);
	setTouchLEDColor(touchLED, colorViolet);
	sleep(2000);
}
