#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMultipleMotors(50, leftMotor, rightMotor, , );
	repeat (forever) {
		if (getUSDistance(sonarSensor) < 20) {
			backward(2, rotations, 50);
			stopAllMotors();
		}
	}
}
