#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Forward for Distance with Encoders

This program instructs the robot to move forward for 5 rotations of the left shaft encoder.
There is a two second pause at the beginning of the program.

The used for feedback should be cleared just before it starts counting  using the
"nMotorEncoder(encoder) = 0;".  This helps ensure consistancy.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          NXT Motor             Right side motor
Motor Port 3        leftMotor           NXT Motor             Left side motor

----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);  // 2 Second Delay

  //Clear Encoders
  nMotorEncoder[rightMotor] = 0;
  nMotorEncoder[leftMotor] = 0;

  while(nMotorEncoder[leftMotor] < 1800)  // While less than 5 rotations on the leftEncoder...
  {
    //...Move Forward
    motor[rightMotor] = 50;
    motor[leftMotor] = 50;
  }

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
