#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	turnLeft(2, seconds, 50);
	wait(1, seconds);
	turnRight(3500, milliseconds, 75);
	wait(1, seconds);
}
