#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lineFollower,   sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Mission Insertion Point (Natural Language)
- This program will cause the robot to pick up the Charge Cube and Deliver it to the Communication
	Tower Pad in Sector 1.
- Your robot will wait for 2 seconds before beginning, move forward at half power for 3.5 rotations
	of the right motor encoder (a sensor that detects how much your wheels have spun), and then stop.
- ROBOTC must be in Natural Language mode for this program to run. You can set this in the top menu
	by going to Robot > Platform Type > LEGO Mindstorms > Natural Language (NXT).
*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]                   [Description]
Motor Port B        rightMotor          Motor w/ Encoder       	 Right side motor
Motor Port C        leftMotor           Motor w/ Encoder       	 Left side motor
----------------------------------------------------------------------------------------------------*/

//Every program has a task main(). All commands that the robot follows go between the curly braces.
task main()
{	//The program begins.
	wait(2.0);		//The robot will wait for 2 seconds before executing commands.

	forward(3.5, rotations, 50); //The robot moves forward at power level 50, which is half power...
															 //...until 3.5 rotations of the motor encoders have been detected.
															 // When it has reached 3.5 rotations, the robot will stop.
}	//The program ends.
