#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(lightSensor) < 45)
	{
		printf("lightSensor");
		motor[motorC] = 0;
		motor[motorB] = 80;
	}
	while(SensorValue(lightSensor) >= 45)
	{
		printf("lightSensor");
		motor[motorC] = 80;
		motor[motorB] = 0;
}
