#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		motor[motorC] = 20;
		motor[motorB] = 20;
		    wait1Msec(3000);
	while(SensorValue(sonarSensor) > 5)
	{
		motor[motorC] = 20;
		motor[motorB] = 20;

	}
	//turn  Left and move
		motor[motorC] = 20;
	  motor[motorB] = 0;
    wait1Msec(3000);
		while(SensorValue(sonarSensor) > 31)
		{
			motor[motorB] = 20;
			motor[motorC] = 20;

		}
		//turn left again
		motor[motorC] = 20;
	  motor[motorB] = 0;
    wait1Msec(3000);
		while(SensorValue(sonarSensor) > 20)
		{
			motor[motorB] = 20;
			motor[motorC] = 20;

		}
}
