#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This program demonstrates how to write functions that use
// encoders to control a robot moving straight and turning.

void moveUntilDistance(int distanceInDegrees)
{
  resetMotorEncoder(rightMotor); // Reset the right motor encoder
  resetMotorEncoder(leftMotor);  // Reset the left motor encoder
  moveMotorTarget(rightMotor, distanceInDegrees, 75); //Move the motors to the "distanceInDegree" value.
  moveMotorTarget(leftMotor, distanceInDegrees, 75);
  waitUntilMotorStop(rightMotor);  //Wait until the motor has come to a stop before moving on.
  waitUntilMotorStop(leftMotor);
}

void pointTurnRight(int turnDistanceRight)
{
  resetMotorEncoder(rightMotor); // Reset the right motor encoder
  resetMotorEncoder(leftMotor);  // Reset the left motor encoder
  moveMotorTarget(rightMotor, turnDistanceRight, -75);//Move the motors to the "distanceInDegree" value.
  moveMotorTarget(leftMotor, turnDistanceRight, 75);
  waitUntilMotorStop(rightMotor);//Wait until the motor has come to a stop before moving on.
  waitUntilMotorStop(leftMotor);
}

void pointTurnLeft(int turnDistanceLeft)
{
  resetMotorEncoder(rightMotor); // Reset the right motor encoder
  resetMotorEncoder(leftMotor);  // Reset the left motor encoder
  moveMotorTarget(rightMotor, turnDistanceLeft, 75);//Move the motors to the "distanceInDegree" value.
  moveMotorTarget(leftMotor, turnDistanceLeft, -75);
  waitUntilMotorStop(rightMotor);//Wait until the motor has come to a stop before moving on.
  waitUntilMotorStop(leftMotor);
}

task main()
{
  moveUntilDistance(960); //change the value of 960 to change the distance traveled or distanced turned.
  pointTurnLeft(960);
  pointTurnRight(960);
}
