#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This program is a very simple example of writing functions to
// move forward, backward, rightTurn, and leftTurn.

void moveForward(int forwardTime)
{
	setMotorSpeed(leftMotor, 75);
	setMotorSpeed(rightMotor, 75);
  sleep(forwardTime);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
  sleep(1000);
}

void moveBackward(int backwardTime)
{
	setMotorSpeed(leftMotor, -75);
	setMotorSpeed(rightMotor, -75);
  sleep(backwardTime);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
  sleep(1000);
}

void rightTurn(int rightTurnTime)
{
	setMotorSpeed(leftMotor, -75);
	setMotorSpeed(rightMotor, 75);
  sleep(rightTurnTime);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
  sleep(1000);
}

void leftTurn(int leftTurnTime)
{
	setMotorSpeed(leftMotor, 75);
	setMotorSpeed(rightMotor, -75);
  sleep(leftTurnTime);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
  sleep(1000);
}

task main()
{
  moveForward(2500);   //change the values passed to change how long the
  moveBackward(3000);  //robot moves forward, backward, or turns
  rightTurn(800);
  leftTurn(1200);
}
