#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeatUntil (SensorValue[touch] == 1) {
		lineTrackLeft(S1, 40, 60, 20);
	}
}
