#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program uses a "do-while" loop to instruct your robot to traverse a square 5 times by
  repeating moving forward and turning behaviors 20 times.
  There is a two second pause at the beginning of the program.

    2)  When using "do-while" loops, the code between its braces is always run at least once,
        since the condition is not checked until after it is run.
    3)  The integer variable 'i' is needed to keep track of the number of times that the
        "do-while" loop has run.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor (Reversed)		  Left side motor
    Port 6       				rightMotor          VEX IQ Motor 							  Right side motor

------------------------------------------------------------------------------------------------*/

task main()
{
	int i = 0;									          // Declares integer variable 'i' and initializes it to 0

	do	// Using "do" guarantees the code will be run at least once since the condition is checked after each iteration, not before
	{

		//Move forward at half power for 2 seconds
		setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
		setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
		sleep(2000);										//Wait for 2 seconds before continuing on in the program.

		//Turn Left at half power for 0.5 seconds
		setMotorSpeed(leftMotor, -50);	//Set the leftMotor (motor1) to half power reversed (-50)
		setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
		sleep(500);											//Wait for 0.5 seconds before continuing on in the program.

		i++;										            // increment i by 1 (same as "i = i + 1")

	}
	while(i < 20);	// This do-while() loop repeats the code above while 'i' is less than 20
}														            // Program ends, and the robot stops
