#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetGyro(port4);
	setMotor(leftMotor, 50);
	setMotor(rightMotor, -50);
	waitUntil (getGyroDegrees(gyroSensor) <= -90);
	stopMultipleMotors(leftMotor, rightMotor, rightMotor, rightMotor);
}
