#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetTimer(T1);
	repeat (forever) {
		if (getTimer(T1, seconds) < 2.50) {
			setTouchLEDColor(port3, colorBlue);
		} else {
			setTouchLEDColor(port3, colorRed);
		}
	}
}
