#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		if (getColorName(colorDetector) == colorBlue) {
			setTouchLEDColor(touchLED, colorBlue);
		}
		if (getColorName(colorDetector) == colorRed) {
			setTouchLEDColor(touchLED, colorRed);
		}
		if (getColorName(colorDetector) == colorGreen) {
			setTouchLEDColor(touchLED, colorGreen);
		}
	}
}
