#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	setMultipleMotors(50, leftMotor, rightMotor, rightMotor, rightMotor);
	waitUntil (getColorName(colorDetector) == colorRed);
	stopMultipleMotors(leftMotor, rightMotor, rightMotor, rightMotor);
}
