#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  extensionEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, dgtl11)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, dgtl5)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Fantasticbot Remote Control
- This program allows you to remotely control your robot using the USB Logitech Dual
  Action Joysticks.
- This program also ignores low values that would cause your robot to move when the joysticks fail to
  return back to exact center.  You may need to adjust the 'threshold' value to get it just right.
- For USB values to be transmitted to the robot, you must follow several steps:
  - Use the "#include "JoystickDriver.c"" line at the beginning of your program
  - Call the "getJoystickSettings(joystick);" in a loop to repeatedly retrieve the latest values
  - Open the Robot > Debugger Windows > "Joystick Control - Basic" window after downloading your
    program to the virtual robot
----------------------------------------------------------------------------------------------------*/

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
  //less than the threshold will be ignored.
  int threshold = 10;

  //Loop Forever
  while(1 == 1)
  {
    //Get the Latest joystick values
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y2) > threshold)  // If the right analog stick's Y-axis readings are either above or below the threshold...
    {
      // ...the right motors are assigned a power level equal to the right analog stick's Y-axis reading.
      motor[frontRightMotor] = joystick.joy1_y2;
      motor[rearRightMotor] = joystick.joy1_y2;
    }
    else                                    // Else the readings are within the threshold, so
    {
      // ...the right motors are stopped with a power level of 0.
      motor[frontRightMotor] = 0;
      motor[rearRightMotor] = 0;
    }

    if(abs(joystick.joy1_y1) > threshold)  // If the left analog stick's Y-axis readings are either above or below the threshold...
    {
      // ...the left motors are assigned a power level equal to the left analog stick's Y-axis reading.
      motor[frontLeftMotor] = joystick.joy1_y1;
      motor[rearLeftMotor] = joystick.joy1_y1;
    }
    else                                    // Else if readings are within the threshold...
    {
      // ...the left motors are stopped with a power level of 0.
      motor[frontLeftMotor] = 0;
      motor[rearLeftMotor] = 0;
    }

		//Arm Control
    if(joy1Btn(6) == 1)       //If button 6 is pressed...
    {
      motor[armMotor] = 127;      //...raise the arm.
    }
    else if(joy1Btn(8) == 1)  //Else, if button 8 is pressed...
    {
      motor[armMotor] = -63;     //...lower the arm.
    }
    else                      //Else (neither button is pressed)...
    {
      motor[armMotor] = 0;       //...stop the arm.
    }

    //Claw Control
    if(joy1Btn(5) == 1)       //If Button 5 is pressed...
    {
      motor[clawMotor] = 127;     //...close the claw.
    }
    else if(joy1Btn(7) == 1)  //Else, if button 7 is pressed...
    {
      motor[clawMotor] = -127;     //...open the claw.
    }
    else                      //Else (neither button is pressed)...
    {
      motor[clawMotor] = 0;       //...stop the claw.
    }

    //Extension Control
    if(joy1Btn(4) == 1)       //If Button 4 is pressed...
    {
      motor[leftExtendMotor] = 127;     //...extend the arm.
      motor[rightExtendMotor] = 127;
    }
    else if(joy1Btn(2) == 1)  //Else, if button 2 is pressed...
    {
      motor[leftExtendMotor] = -127;     //...retract the arm.
      motor[rightExtendMotor] = -127;
    }
    else                      //Else (neither button is pressed)...
    {
      motor[leftExtendMotor] = 0;     //...stop extending/retracting the arm.
      motor[rightExtendMotor] = 0;
    }

    //Wrist Control
    if(joy1Btn(1) == 1)       //If Button 1 is pressed...
    {
      motor[wristMotor] = 127;     //...turn the wrist up.
    }
    else if(joy1Btn(3) == 1)  //Else, if button 3 is pressed...
    {
      motor[wristMotor] = -127;     //...turn the wrist down.
    }
    else                      //Else (neither button is pressed)...
    {
      motor[wristMotor] = 0;       //...stop the wrist.
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
