#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	while (SensorValue[sound] < 50) {
		// Do nothing (Idle Loop)
	}
	forward(5, rotations, 50);
}
