#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeatUntil (SensorValue[sonar] <= 20) {
		lineTrackRight(S1, 65, 75, 35);
	}
}
