#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(rightMotor, 50);
	sleep(2000);
	setMotorSpeed(rightMotor, 0);
	sleep(1000);

	setMotorSpeed(leftMotor, 50);
	sleep(3500);
}
