#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	moveMotorTarget(armMotor, 40, 50);
	sleep(2000);
	moveMotorTarget(armMotor, -80, 50);
	sleep(2000);
}
