#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program uses a "while" loop to instruct the robot to traverse a square 5 times by repeating
	moving forward and turning behaviors 20 times.

    NOTES:
    1)  A "while" loop checks the condition (the code following 'while' between the parenthesis)
        each time before the code inside of the braces is run
        (or skipped, if conditions are not met).
    2)  The integer variable 'i' is needed to keep track of the number of times that the "while"
        loop has run.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
task main()
{
	int i = 0;									        // Declares integer variable 'i' and initializes it to 0

	while(i < 20)	//This while() loop repeats the code below while 'i' is less than 20
	{
		//Move forward at half power for 2 seconds
		setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
		setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
		sleep(2000);										//Wait for 2 seconds before continuing on in the program.

		//Turn Left at half power for 0.5 seconds
		setMotorSpeed(leftMotor, -50);	//Set the leftMotor (motor1) to half power reversed (-50)
		setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
		sleep(500);											//Wait for 0.5 seconds before continuing on in the program.

		i++;										          // Increment 'i' by 1 (same as "i = i + 1")
	}
}// Program ends, and the robot stops
