#pragma config(StandardModel, "REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  nMotorEncoder[leftMotor] = 0;
  nMotorEncoder[rightMotor] = 0;
  nMotorEncoderTarget[leftMotor] = 2880;
  nMotorEncoderTarget[rightMotor] = 2880;

  motor[leftMotor] = 40;
  motor[rightMotor] = 40;
  while(nMotorRunState[leftMotor] != runStateIdle || nMotorRunState[rightMotor] != runStateIdle)
  {

  }
}
