#pragma config(Sensor, S3,     lightsensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This program allows the robot to go forward until it sees a black line

task main()
{
	int threshold = 44;

	while(SensorValue[lightsensor] > threshold)
	{

		motor[motorC] = 100;
		motor[motorB] = 100;

	}

	motor[motorC] = 0;
	motor[motorB] = 0;

}
