#pragma config(Sensor, S3,     RightLightSensor, sensorLightActive)
#pragma config(Sensor, S4,     LeftLightSensor, sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This program uses the light sensor to track the left side of a line

task main()
{
	int threshold = 42;

	while(true)
	{

		if(SensorValue[LeftLightSensor] < threshold)
		{

			motor[motorB]=100;
			motor[motorC]=0;

		}
		else
		{

			motor[motorB]=0;
			motor[motorC]=100;

		}

	}

}
