#pragma config(Sensor, S1,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(SensorValue(sonarSensor) > 25)
	{

		motor[motorC] = 50;
		motor[motorB] = 50;

	}

	motor[motorC] = -50;
	motor[motorB] = -50;
	wait1Msec(2000);

}
