#pragma config(Sensor, S1,     soundSensor,    sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	clearTimer(T1);

	while(time1[T1] < 10000)
	{

		motor[motorC] = SensorValue(soundSensor);
		motor[motorB] = SensorValue(soundSensor);

	}

}
