#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  motorA,          motorD_Encoder, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          motorE_Encoder, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  nMotorEncoder[motorD_Encoder] = 0;
  nMotorEncoder[motorE_Encoder] = 0;

  while(nMotorEncoder[motorD_Encoder] < 1080 || nMotorEncoder[motorE_Encoder] < 1080)
  {
    motor[motorD] = 25;
    motor[motorE] = 25;
  }
}
