#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    armServo,             tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  /*
  motor[motorD] = 50;
	motor[motorE] = 50;
	wait1Msec(3000);
	motor[motorD] = -40;
	motor[motorE] = -40;
	wait1Msec(3000);
	*/

	servo[armServo] = 255;
	wait1Msec(2000);
	servo[armServo] = 0;
	wait1Msec(2000);
}
