#pragma config(Sensor, S1,     bumper,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(SensorValue(bumper) == 0)
	{

		motor[motorC] = 50;
		motor[motorB] = 50;

	}

	motor[motorC] = -50;
	motor[motorB] = -50;
	wait1Msec(2000);

}
