#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// This program will move the robot forward for 1 second, stop,
	// and turn to the left for 2 seconds. It will repeat these behaviors 5 times
	for (int i = 0; i < 5; i++)
	{
		setMotorSpeed(rightMotor, 50);
		setMotorSpeed(leftMotor, 50);
		sleep(1000);
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);

		setMotorSpeed(rightMotor, 50);
		sleep(2000);
		setMotorSpeed(rightMotor, 0);
	}
}
