#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		moveMotorTarget(leftMotor, 360, 50);
		moveMotorTarget(rightMotor, 360, 50);
		while(getMotorRunning(leftMotor) || getMotorRunning(rightMotor))
		{
			sleep(1);
		}
    sleep(2000);
		moveMotorTarget(rightMotor, 640, 50);
		while(getMotorRunning(rightMotor))
		{
			sleep(1);
		}
	}
}
