#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (getTouchValue(touchSensor) == 0)
		{
			setMotorSpeed(rightMotor, 50);
			setMotorSpeed(leftMotor, 50);
		}
		else
		{
			moveMotorTarget(leftMotor, -720, 50);
			moveMotorTarget(rightMotor, -720, 50);
			while(getMotorRunning(leftMotor) || getMotorRunning(rightMotor))
			{
				sleep(1);
			}
			moveMotorTarget(rightMotor, 360, 50);
			while(getMotorRunning(rightMotor))
			{
				sleep(1);
			}
		}
	}
}
