#pragma config(Sensor, port7, distanceSensor,     sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
Move forward until the VEX IQ Distance Sensors sees an object 100 millimeters (mm) away. The VEX
IQ Distance Sensor returns values in millimeters.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Info]
Port 7        			distanceSensor      VEX IQ Distance		      		Distance Sensor (returns mm)
Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	//While distance sensor is more than 100mm (10cm) away
	while(getDistanceValue(distanceSensor) > 100)
	{
		setMotorSpeed(leftMotor, 50);  //Move left motor at 50% speed
		setMotorSpeed(rightMotor, 50); //Move right motor at 50% speed
	}
}
