#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**************************\
|*  ROBOTC Virtual World  *|
|*  Turning with Encoders *|
\**************************/

// This program makes a sharp turn using the encoders for reproducable accuracy.

task main()
{
  SensorValue[rightEncoder] = 0;          // reset encoder to 0

  while(SensorValue[rightEncoder] < 100)  // while the right encoder value is less than 100:
  {
                                      // turn LEFT in place:
    motor[rightMotor] = 75;           // set port2 to speed 75
    motor[leftMotor]  = -75;          // set port3 to speed 75
  }
                                      // stop the robot:
  motor[rightMotor] = 0;              // set port2 to speed 0
  motor[leftMotor]  = 0;              // set port3 to speed 0
}
