#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeatUntil (getUSDistance(sonarSensor) < 20) {
		setMotor(rightMotor, 50);
		setMotor(leftMotor, 50);
	}
	stopAllMotors();
}
