#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMultipleMotors(50, rightMotor, leftMotor, , );
	waitUntil (getColorReflected(colorSensor) < 30);
	stopAllMotors();
}
