#pragma config(Sensor, S1,     touchSensor,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                          - Go until Push -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program allows your taskbot to move forward indefinately while monitoring a Touch Sensor.        *|
|*  If the Touch Sensor is bumped, the robot will reverse and stop.                                       *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Touch Sensor should be mounted on the front.                                                *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  touchSensor         Touch Sensor        Front mounted                       *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
  while(SensorValue(touchSensor) == 0)    // While the Touch Sensor is inactive (hasn't been pressed):
  {
    motor[motorB] = 100;                        /* Run motors B and C forward */
    motor[motorC] = 100;                        /* with a power level of 100. */
  }
                                          // Otherwise (the touch sensor has been activated [pressed] ):
  motor[motorB] = -75;                    /* Run motors B and C backwards */
  motor[motorC] = -75;                    /* with a power level of -75.   */

  wait1Msec(1000);                        // Wait 1000 milliseconds (1 second) before moving to further code.
}
