#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                          - Wait for Push -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program keeps your robot in place and won't run the program until you push the Touch Sensor.     *|
|*  The first while loop waits for the Touch Sensor to be pressed.  The second while loop waits for the   *|
|*  Touch Sensor to be released.                                                                          *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Touch Sensor should be mounted on the top.                                                  *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  touchSensor         Touch Sensor        Front mounted                       *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
  while(SensorValue(touchSensor) == 0)    // While the Touch Sensor is inactive (hasn't been pressed):
  {
    // DO NOTHING (wait for press)
  }

  while(SensorValue(touchSensor) == 1)    // While the Touch Sensor is active (pressed):
  {
    // DO NOTHING (wait for release)
  }
                                          // Otherwise (the touch sensor has been activated [pressed] ):
  motor[motorB] = 75;                     /* Run motors B and C forwards */
  motor[motorC] = 75;                     /* with a power level of 75.   */

  wait1Msec(1000);                        // Wait 1000 milliseconds (1 second) before moving to further code.
}
