#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	forward(3, seconds, 50);
	wait(2, seconds);
	backward(3, seconds, 50);
}
