#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	moveMotor(rightMotor, 2, rotations, 50);
	wait(2, seconds);
	moveMotor(leftMotor, 2, seconds, -35);
}
