#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	turnLeft(2, rotations, 55);
	wait(1, seconds);
	turnRight(150, degrees, 45);
	wait(1, seconds);
}
