#pragma config(Sensor, S1,     touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                       "Try Me" Program for NXT Touch Sensor
//
///////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma fileExtension("rtm")
#pragma platform("NXT")


task main()
{
	static bool bFirstTime = true;
	//
	// Grab LCD screen and initialize display
	//
	eraseDisplay();
	displayCenteredBigTextLine(0, "Touch");
	displayCenteredTextLine(3, "Connect Sensor");
	displayCenteredTextLine(4, "to Port S1");
	wait1Msec(100);

	while (true)
	{
	  if (SensorBoolean[touch])
	  {
	  	bFirstTime = false;
    	displayClearTextLine(1);
    	displayClearTextLine(3);
			displayClearTextLine(4);

	  	playSoundFile("Woops.rso");
			displayRICFile(27, 8, "faceOpen.ric");
	    displayCenteredTextLine(0, "Touch");
			displayCenteredTextLine(7, "Pressed");
		  while (SensorBoolean[touch])
		  {}
		  clearSounds();
		}
		else
		{
			if (!bFirstTime)
			{
		  	displayRICFile(27, 8, "faceclosed.ric");
	      displayCenteredTextLine(0, "Touch");
				displayCenteredTextLine(7, "Released");
			}
		}
	}
}
