#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat (forever) {
		tankControl(JoyY2, JoyY1, 10);
		armControl(armMotor, Btn5, Btn7, 75);
	}
}
