#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeatUntil (getTimer(T1, seconds) < 10) {
		lineTrackRight(colorDetector, 50, 50, 0);
	}
}
