#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	stopMotor(rightMotor);
	setMotor(leftMotor, 50);
	wait(1, seconds);
	stopAllMotors();
}
