#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Servo Control by NXT Motor -                                      *|
|*                                        ROBOTC on NXT + TETRIX                                          *|
|*                                                                                                        *|
|*  This program uses the encoder values of an NXT Motor to set the position of a servo.  The purpose of  *|
|*  this program is to make it simple to manually test and set a servo to the position of your liking.    *|
|*  The motor and arrow keys adjust servo position.  When the Center Orange Button is active, the servo   *|
|*  will jump by increments of 10.  The servo position and encoder values are displayed.                  *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  Make sure you attach an NXT motor equipped with some way to manually turn it. (gear / wheel)    *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Chan. 1        servo1              std. Servo          The servo that you wish to test.    *|
|*    Port A                  motorA              NXT Motor           With some way to manually turn it.  *|
|*                                                                                                        *|
|*                                        Button Layout (NXT)                                             *|
|*                                               _____                                                    *|
|*                                         /|   |     |   |\                                              *|
|*                                        / |   |     |   | \                                             *|
|*                                       / 2|   |  3  |   |1 \                                            *|
|*                                       \ 2|   |  3  |   |1 /                                            *|
|*                                        \ |   |     |   | /                                             *|
|*                                         \|   |_____|   |/                                              *|
|*                                                                                                        *|
|*                                     NXT Screen Size ~ 100 x 64                                         *|
|*                                                                                                        *|
\*---------------------------------------------------------------------------------------------------4246-*/


int e = 0;                   // Create variable 'e' which will set the encoder.

const int encUpB = 256;      // Create a constant 'encUpB' to hold encoder upper bound (numerically, NOT mechanically)!
const int encLwB = 0;        // Create a constant 'encLwB' to hold encoder lower bound (numerically, NOT mechanically)!

bool orngBtn = false;        /* Create boolean 'orngBtn' to hold whether or not the Center Orange Button
	                                of the NXT has been pressed or not. */

//-------------------------------------------------------------------------------------------------------------------------------------

bool CheckEncoderBoundsBOTH(int up, int dn)                             /* Checks to see if the passed values are within both the */
{                                                                       /* upper and lower bounds [inclusive] of the servo.       */
  if(nMotorEncoder[motorA] <= up  &&  nMotorEncoder[motorA] >= dn)
  {
    return true;
  }
  else
  {
    return false;
  }
}

//-------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------------------------

bool CheckEncoderBoundsUP(int up)                                       /* Checks to see if the passed value is within the upper */
{                                                                       /* bound [inclusive] of the servo.                       */
  if(nMotorEncoder[motorA] <= up)
  {
    return true;
  }
  else
  {
    return false;
  }
}

//-------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------------------------

bool CheckEncoderBoundsDOWN(int dn)                                     /* Checks to see if the passed value is within the lower */
{                                                                       /* bound [inclusive] of the servo.                       */
  if(nMotorEncoder[motorA] >= dn)
  {
    return true;
  }
  else
  {
    return false;
  }
}

//-------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------------------------

void Display()                                                          // Displays both Servo Position and Encoder Value
{
                                                                        //            NXT Display
  displayCenteredTextLine(0, "Servo Position");                      //         __________________
  displayCenteredBigTextLine(2, "%d", e);                            //        |  Servo Position  |
                                                                        //        |      ##  ##      |
  displayCenteredTextLine(5, "%d", nMotorEncoder[motorA]);           //        |      ##  ##      |
  displayCenteredTextLine(7, "Encoder Position");                    //        |                  |
                                                                        //        |        ##        |
  wait1Msec(25);      // Update screen every 25 milliseconds            //        |__Encoder  Value__|
}

//-------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------------------------

void ToggleOrangeButton()                                               /* When the Orange Button is pressed, this checks to see */
{                                                                       /* whether or not it has already been pressed.           */
  if(orngBtn == false)
  {
    displayCenteredTextLine(4, "<<     >>");
    orngBtn = true;                                                     // If not yet active, activate.
  }
  else
  {
    displayClearTextLine(4);
    orngBtn = false;                                                    // If already active, deactivate.
  }
}

//-------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------------------------

void LeftArrowBtn()                                                     /* Moves the servo position DOWN by increments of 1 */
{                                                                       /* or 10 depending on whether or not the orange     */
  if(orngBtn == true)                                                   /* button has been activated or not.                */
  {
    if(CheckEncoderBoundsDOWN(encLwB+10))     //---------------------//|
    {                                                                //|
      e -= 10;                                                       //|
                                                                     //|
      while(nMotorEncoder[motorA] > e)                               //|
      {                                                              //|
        motor[motorA] = -5;                                          //|=== Decrement by 10
      }                                                              //|
                                                                     //|
      motor[motorA] = 0;                                             //|
      servo[servo1] = e;                                             //|
    }                                                                //|
  }                                           //---------------------//|
  else
  {
    if(CheckEncoderBoundsDOWN(encLwB+1))      //---------------------//|
    {                                                                //|
      e--;                                                           //|
                                                                     //|
      while(nMotorEncoder[motorA] > e)                               //|
      {                                                              //|
        motor[motorA] = -30;                                         //|=== Decrement by 1
      }                                                              //|
                                                                     //|
      motor[motorA] = 0;                                             //|
      servo[servo1] = e;                                             //|
    }                                                                //|
  }                                           //---------------------//|
}

//-------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------------------------------------------

void RightArrowBtn()                                                    /* Moves the servo position UP by increments of 1   */
{                                                                       /* or 10 depending on whether or not the orange     */
  if(orngBtn == true)                                                   /* button has been activated or not.                */
  {
    if(CheckEncoderBoundsUP(encUpB-10))       //---------------------//|
    {                                                                //|
      e += 10;                                                       //|
                                                                     //|
      while(nMotorEncoder[motorA] < e)                               //|
      {                                                              //|
        motor[motorA] = 5;                                           //|===Increment by 10
      }                                                              //|
                                                                     //|
      motor[motorA] = 0;                                             //|
      servo[servo1] = e;                                             //|
    }                                         //---------------------//|
  }
  else
  {
    if(CheckEncoderBoundsUP(encUpB-1))        //---------------------//|
    {                                                                //|
      e++;                                                           //|
                                                                     //|
      while(nMotorEncoder[motorA] < e)                               //|
      {                                                              //|
        motor[motorA] = 30;                                          //|===Increment by 1
      }                                                              //|
                                                                     //|
      motor[motorA] = 0;                                             //|
      servo[servo1] = e;                                             //|
    }                                                                //|
  }                                           //---------------------//|
}

//-------------------------------------------------------------------------------------------------------------------------------------

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
  while(true)
  {

    // MOTOR CONTROL
    if(CheckEncoderBoundsBOTH(encUpB, encLwB))
    {
      e = nMotorEncoder[motorA];
      servo[servo1] = e;
    }


    // BUTTON CONTROL
    if(nNxtButtonPressed == 3)            // If Center Button is pressed
    {
      while(nNxtButtonPressed != -1){}
      ToggleOrangeButton();
    }
    if(nNxtButtonPressed == 2)            // If Left Arrow Button is pressed
    {
      LeftArrowBtn();
    }

    if(nNxtButtonPressed == 1)            // If Right Arrow Button is pressed
    {
      RightArrowBtn();
    }


    // DISPLAY TO SCREEN
    Display();

  }
}

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
