#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeatUntil (SensorValue[sonar] < 20) {
		setMotor(motorB, 50);
		setMotor(motorC, 50);
	}
	stopAllMotors();
}
