#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	stopMotor(motorB);
	setMotor(motorC, 50);
	wait(1, seconds);
	stopAllMotors();
}
