#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetTimer(T1);
	repeatUntil (getTimer(T1, seconds) > 10) {
		setTouchLEDHue(port3, 100);
		wait(250, milliseconds);
		setTouchLEDColor(port3, colorViolet);
		wait(.25, seconds);
		setTouchLEDRGB(port3, 100, 0, 150);
		wait(1/4, seconds);
	}
}
