#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	setTouchLEDColor(port3, colorYellow);
	wait(1, seconds);
	setTouchLEDColor(port3, colorDarkOrange);
	wait(1, seconds);
	setTouchLEDColor(port3, colorBlue);
	wait(1, seconds);
}
