#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		if (getTouchLEDValue(touchLED) == 1) {
			setTouchLEDColor(port3, colorRed);
		} else {
			setTouchLEDColor(port3, colorBlue);
		}
	}
}
