#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will show how you can use a non-blocking command to perform other tasks while your
  motors are moving to a specific position. The motors will begin moving to position 5000, and
  while they're moving we'll display the current encoder value to the

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)

------------------------------------------------------------------------------------------------*/

task main
{
	resetMotorEncoder(leftMotor);		//Reset the current position in the motor encoder to zero.
	resetMotorEncoder(rightMotor);
	moveMotorTarget(leftMotor, 5000, 75);  //Set motor to run 5000 counts at power level 75.
	moveMotorTarget(rightMotor, 5000, 75);

	wait1Msec(50); //Small delay to allow motors time to start moving before checking

	//getMotorMoving - Flag to indiciate if the motor is moving (True - Moving / False - Stopped)
	//Loop while either motor is still moving (Left OR Right is still moving)
	while(getMotorMoving(leftMotor) || getMotorMoving(rightMotor))
	{
		//Print
		displayTextLine(1, "Left Motor: %d", getMotorEncoder(leftMotor));
		displayTextLine(3, "Right Motor: %d", getMotorEncoder(rightMotor));
		sleep(50);
	}
}
