#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	setTouchLEDRGB(port3, 0, 0, 255);
	wait(1, seconds);
	setTouchLEDRGB(port3, 0, 255, 0);
	wait(1, seconds);
	setTouchLEDRGB(port3, 255, 0, 0);
	wait(1, seconds);
	setTouchLEDRGB(port3, 255, 255, 255);
}
