#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	forward(2.5, rotations, 50);
	forward(540, degrees, 50);
	forward(1500, milliseconds, 50);
	forward(1.25, seconds, 50);
	forward(.1, minutes, 50);
}
