#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetMotorEncoder(leftMotor);
	setMotor(leftMotor, 50);
	waitUntil (getMotorEncoder(leftMotor) > 360);
	stopMotor(leftMotor);
}
