#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)//remember to enable external motor/servo controllers under Robot/Platform Type
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                            - FOR Loop -                                                *|
|*                                       ROBOTC on NXT + TETRIX                                           *|
|*                                                                                                        *|
|*  This program runs your TETRIX robot in a square five times.                                           *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  Remember to use 'Robot -> Motors and Sensors Setup'to set up your motor configuration.          *|
|*    2)  If using kit TETRIX bot, remember to reverse Motor E in 'Motor and Sensor Setup'.               *|
|*    3)  You may need to change the wait times used to achieve a 90 degree turn.  Experiment to find     *|
|*        the perfect values and your robot should end facing the same direction that it started.         *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Motor 1        motorD              12V                 Right motor                         *|
|*    Port 1 - Motor 2        motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
   int i;                    //the variable "i" is declared as an integer

   //a for loop is declared that: intializes i equal to zero
   //continues to run under the condition i is less than 20
   //and increments i by one after each iteration
   for(i = 0; i< 20; i++)
   {
      motor[motorD] = 25;    // Motor D is run at a 75 power level.
      motor[motorE] = 25;    // Motor E is run at a 75 power level.
      wait1Msec(4000);       // The program waits 4000 milliseconds before running further code.

      motor[motorD] = 25;    // Motor D is run at a 75 power level.
      motor[motorE] = -25;   // Motor E is run at a -75 power level.
      wait1Msec(750);        // The program waits 750 milliseconds before running further code.
   }
}
