#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		arcadeControl(ChA, ChB, 10);
		armControl(motor10, BtnLUp, BtnLDown, 75);
		armControl(motor11, BtnRUp, BtnRUp, 75);
	}
}
