#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
	This program will show the VEX IQ Color sensor in "12 Color" mode. This mode will return a specific
	color values as opposed to a "Hue" value. This is helpful for detecting specific colors.

	The 12 valid color names are:
	colorRedViolet / colorRed / colorDarkOrange / colorOrange /	colorDarkYellow /	colorYellow /
	colorLimeGreen / colorGreen /	colorBlueGreen / colorBlue / colorDarkBlue /  colorViolet

	the "getColor12Color" command will return one of the 12 named colors, so a simple "equal to"
	works the best. This program will use a "switch case" to detect the 12 colors.

	ROBOT CONFIGURATION: VEX IQ Clawbot
	MOTORS & SENSORS:
	[I/O Port]          [Name]              [Type]                			[Location]
	Port 5       				colorDetector       VEX IQ Color		      			Color Detector (12 Color Mode)
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		//The switch command tells us which value we want to check against.
		switch(getColorName(colorDetector))
		{
			//Each "case" is the color we want to check for. Once we find a color, we'll print it to the screen.
			//Each "case" must end with a "break" command to say we're done in the "switch" and continue on with the program.
			case colorRedViolet:
			{
				displayTextLine(1, "Color: Red Violet");
				break;
			}
			case colorRed:
			{
				displayTextLine(1, "Color: Red");
				break;
			}

			//Case statements can also be written without curly brackets to save time.
			//The case will continue running code until it sees a "break".
			case colorDarkOrange:	displayTextLine(1, "Color: Dark Orange");		break;
			case colorOrange:			displayTextLine(1, "Color: Orange");				break;
			case colorDarkYellow:	displayTextLine(1, "Color: Dark Yellow");		break;
			case colorYellow:			displayTextLine(1, "Color: Yellow");				break;
			case colorLimeGreen:	displayTextLine(1, "Color: Lime Green");		break;
			case colorGreen:			displayTextLine(1, "Color: Green");					break;
			case colorBlueGreen:	displayTextLine(1, "Color: Blue Green");		break;
			case colorBlue:				displayTextLine(1, "Color: Blue");					break;
			case colorDarkBlue:		displayTextLine(1, "Color: Dark Blue");			break;
			case colorViolet:			displayTextLine(1, "Color: Violet");				break;
		}
		sleep(25);	//Small Delay to allow a new color to be detected.
	}
}
