#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program shows how you can adjust the brightness of the Touch LED without having to change
  color values. This allows you to set "dimmer" or "brighter" versions of pre-set colors.

  Brightness values range from 0 to 255, with 255 being the brightest. Setting the brightness
  to a value of 0 will turn the Touch LED off.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    port 12							touchLED						VEX IQ Touch LED						Detect Touches and Set Colors
------------------------------------------------------------------------------------------------*/

task main()
{
	setTouchLEDColor(touchLED, colorRed);
	sleep(1000);

	setTouchLEDBrightness(touchLED, 200);
	sleep(1000);

	setTouchLEDBrightness(touchLED, 150);
	sleep(1000);

	setTouchLEDBrightness(touchLED, 100);
	sleep(1000);

	setTouchLEDBrightness(touchLED, 0);
	sleep(1000);
}
