#pragma config(Motor,  motor1,          HourHand,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor2,          MinuteHand,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long nTotalMinutes = 0;
long nMinutes = 0;
long nHours	 = 0;
long nTimeAcceleration = 100;
int  nMotorSpeed = 200;

void resetClock()
{
	nTotalMinutes = 0;
	nMinutes = 0;
	nHours	 = 0;
	setMotorTarget(HourHand, nMotorSpeed, 0);
	setMotorTarget(MinuteHand, nMotorSpeed, 0);
	while (true)
	{
		long nEncoder;
		sleep(1);
		nEncoder = getMotorEncoder(HourHand);
		if ((nEncoder > 5) && (nEncoder < - 5))
			continue;

		nEncoder = getMotorEncoder(MinuteHand);
		if ((nEncoder > 5) && (nEncoder < - 5))
			continue;
		break;
	}
}

void moveClockHands()
{
	long nPosition;
	const long kTicksPerRevolutionMinutes = 960 * 3;
	const long kTicksPerRevolutionHours   = 960;

	nPosition = (nTotalMinutes * kTicksPerRevolutionMinutes) / 60;
	setMotorTarget(MinuteHand, nPosition, nMotorSpeed);

	nPosition = (nTotalMinutes * kTicksPerRevolutionHours) / 60 / 12;
	setMotorTarget(HourHand, nPosition, nMotorSpeed);
}

void minuteTick()
{
	++nTotalMinutes;
	++nMinutes;
	if (nMinutes >= 60)
	{
		nMinutes = 0;
		++nHours;
		if (nMinutes >= 12)
			nHours = 0;
	}
	moveClockHands();
}

task main()
{
	resetClock();
	while (true)
	{
		sleep(60000 / nTimeAcceleration);
		minuteTick();
	}
	return;
}
