#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Keep looping forever
	repeat(forever)
	{
		//Control the robot with Tank Control style driving
		tankControl(ChD, ChA, 10);
		//Control the arm motor with buttons RUp and RDown
		armControl(armMotor, BtnRUp, BtnRDown, 50);
		//Control the claw motor with buttons EUp and EDown
		armControl(clawMotor, BtnEUp, BtnEDown, 50);

		//If the Color Sensors sees Blue or Green
		if(getColorName(colorDetector) == colorBlue || getColorName(colorDetector) == colorGreen)
		{
			//Display "Safe to Grab" on line 1 of the LCD screen
			displayTextLine(1, "Safe to Grab");
		}

		//Else (the Color Sensor sees a color that is NOT Blue or Green)
		else
		{
			//Display "Dangerous" on line 1 of the LCD screen
			displayTextLine(1, "Dangerous");
		}
		//Display the text for 20 milliseconds and clear the screen
		sleep(20);
		eraseDisplay();
	}
}
