#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the Capacitive Touch functionality of the Touch LED to toggle between two
  colors. Note that the Capacitive Touch will only work with the touch of a hand, so do not mount
  this sensor to detect the touch of a wall or other inanimate object.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    port 12							touchLED						VEX IQ Touch LED						Detect Touches and Set Colors
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		if(getTouchLEDValue(touchLED) == 0)  //Touch LED is not pressed
		{
			setTouchLEDRGB(touchLED, 0, 255, 0);  //Set as Green Color
		}
		else																 //Touch LED is pressed
		{
			setTouchLEDRGB(touchLED, 255, 0, 0);	//Set as Red Color
		}
		sleep(25);
	}
}
