#pragma config(Sensor, S1,     soundSensor,         sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                            - Clap  Off -                                               *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your robot forward until a loud noise is made.                                      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The 1 second delay is needed to avoid obtaining inaccurate initial readings.                    *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
|*    Port 1                  soundSensor         Sound Sensor        Sound Db                            *|
\*---------------------------------------------------------------------------------------------------4246-*/

task main()
{
	wait1Msec(1000);                        // Wait for 1 second to ignore initial readings of the Sound Sensor.

	while(SensorValue(soundSensor) < 70)    // While the Sound Sensor is less than 70 (quiet):
	{
		motor[motorC] = 75;                       // Motor C is run at a 75 power level.
		motor[motorB] = 75;                       // Motor B is run at a 75 power level.
	}

	motor[motorC] = 0;                      /* Otherwise, when loud noises are heard, Motor C */
	motor[motorB] = 0;                      /* and motor B stop.                              */

}
