#pragma config(Sensor, S2,     soundSensor,         sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                           - Sound Drive -                                              *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your robot at a speed related to the volume of the noise that it hears.             *|
|*  The louder the sound, the faster the robot will go.  Likewise the quieter, the slower it will go.     *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The 1 second delay is needed to avoid obtaining inaccurate initial readings.                    *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 1                  soundSensor         Sound Sensor        Sound Db                            *|
\*---------------------------------------------------------------------------------------------------4246-*/

task main()
{
   wait1Msec(1000);       // A one-second wait is required to cleanly initialize the Sound Sensor.

   while(true)            // Infinite loop
   {
     motor[motorB] = SensorValue[soundSensor];    /* Motors B and C are run at a power level equal */
     motor[motorC] = SensorValue[soundSensor];    /* to the value read in by the Sound Sensor.     */
   }
}
