#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// This program will move the robot forward for 1 second, stop,
	// and turn to the left for 2 seconds. It will repeat these behaviors 5 times
	repeat (5) {
		forward(1, seconds, 50);
		wait(2, seconds);
		turnLeft(1, seconds, 50);
	}
}
