#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat (forever) {
		if (getTouchValue(touchSensor) == 0) {
			setMultipleMotors(50, rightMotor, leftMotor, , );
		} else {
			backward(2, rotations, 50);
			turnLeft(1, rotations, 50);
		}
	}
}
