#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMultipleMotors(50, motorB, motorC, motorC);
	waitUntil (SensorValue[light] < 30);
	stopAllMotors();
}
