#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	setMotor(motorB, 50);
	stopMotor(motorC);
	wait(2500, milliseconds);
	stopAllMotors();
}
