#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeatUntil (getMotorEncoder(leftMotor) <= 1800) {
		lineTrackLeft(colorDetector, 50, 50, 0);
	}
}
