#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setTouchLEDRGB(touchLED, 0, 0, 0);
	sleep(3000);

	while(getColorName(colorDetector) != colorBlueGreen)
	{
		setTouchLEDColor(touchLED, getColorName(colorDetector));
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	setTouchLEDColor(touchLED, colorGreen);
	wait1Msec(2000);
}
