#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeatUntil (getBumperValue(bumpSwitch) == 1) {
		lineTrackRight(colorDetector, 50, 50, 0);
	}
}
