#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait(3, seconds);
	setMotor(rightMotor, 50);
	setMotor(leftMotor, 50);
	wait(2, seconds);
	stopAllMotors();
	wait(1, seconds);
	turnLeft(3, rotations, 50);
}
