#pragma config(Sensor, S2,     lightsensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This program uses the light sensor to track the left side of a line

task main()
{
	int threshold = 43;

	clearTimer(T1);

	while(time1[T1] < 3000)
	{

		if(SensorValue(lightsensor) < threshold)
		{

			motor[motorC]=0;
			motor[motorB]=50;


		}
		else
		{

			motor[motorC]=50;
			motor[motorB]=0;

		}

	}

}
