#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1 == 1)
	{

		while(SensorValue(lightSensor) < 43)
		{

			motor[motorC] = 0;
			motor[motorB] = 80;

		}

		while(SensorValue(lightSensor) > 43)
		{

			motor[motorC] = 80;
			motor[motorB] = 0;

		}

	}

}
