#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	clearTimer(T1);

	while(time1[T1] < 3000)
	{

		if(SensorValue(lightSensor) < 43)
		{

			motor[motorC] = 0;
			motor[motorB] = 80;

		}

		else
		{

			motor[motorC] = 80;
			motor[motorB] = 0;

		}

	}

	motor[motorC] = 0;
	motor[motorB] = 0;

}
