#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//******************************************************************************//
//                              Wait for Light                                  //
//                              ROBOTC on NXT                                   //
//                                                                              //
//  This program allows your taskbot to run forward until it detects a light    //
//  surface.                                                                    //
//																				                                      //
//	Notes							                                                          //
//  1. The light sensor is attached to the back of the robot                    //
//  2. Be sure to take readings of your light sensor over the light and dark    //
//     areas. Once you have the values, add them and divide by 2 to find your   //
//     threshold. Then, use your threshold as a comparison in your program.     //
//                                                                              //
//	Motors & Sensors                          							      	            //
//  [I/O Port]          [Name]          [Type]          [Description]           //
//  Port C              none            Motor           Right Motor             //
//  Port B              none            Motor           Left Motor              //
//  Port 1              lightsensor     Light Sensor    none                    //
//******************************************************************************//


task main()
{
	wait1Msec(50);                        //the program waits 50 millisecond to initialize the light sensor

	while(SensorValue[lightSensor] < 45)   //a loop that will keep looping while the light sensor's value is less than 45.
	{
		motor[motorB] = 75;                //Motor C is run at a 75 power level
		motor[motorC] = 75;                //motor B is run at a 75 power level
	}

	motor[motorB] = 0;                      //Motor C is stopped with a 0 power level
	motor[motorC] = 0;                      //motor B is stopped with a 0 power level
}
