#pragma config(Sensor, S1,     lightSensor,         sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                          - Wait for Dark -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your taskbot forward until it detects a dark surface.                               *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
	wait1Msec(50);                         // The program waits 50 milliseconds to initialize the light sensor.

	while(SensorValue[lightSensor] > 45)   // While the reading is greater than 45 (a light surface):  NOTE- make this less than to detect light surfaces.
	{
		motor[motorB] = 100;                // Motor C is run at a 100 power level.
		motor[motorC] = 100;                // Motor B is run at a 100 power level.
	}

	motor[motorB] = 0;                     // Motor C is stopped with a 0 power level.
	motor[motorC] = 0;                     // Motor B is stopped with a 0 power level.
}

/*NOTE

Instead of stopping the motors when you reach a dark surface, you could also count them using a
variable for the line counting challenge.

*/
