#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This program will use the VEX IQ Gyro sensor to make a 90 degree turn. Note: the loop will end as
soon as the gyro hits 90 degrees, but momentum may carry the robot past the 90 degree point.
Using a lower motor speed can help with this drift/momentum.

Note - Rotation to the Left of the gyro will increase the sensor's value
			 Rotation to the Right of the gyro will decrease the sensors value (the value can be negative)

Note: The VEX IQ Gyro Sensor returns values in degrees.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Info]
Port 7        			gyroSensor		      VEX IQ Distance		      		Gyro Sensor (returns degrees)
------------------------------------------------------------------------------------------------*/

task main()
{
	//Reset the gyro sensor to remove any previous data
	resetGyro(gyroSensor);

	//Loop while the gyro sees a value less than 90 degrees.
	while(getGyroDegrees(gyroSensor) < 90)
	{
		//Set the motors to turn to the left at 25% speed.
		setMotorSpeed(leftMotor, -25);
		setMotorSpeed(rightMotor, 25);
	}

	//Specifically stop the motor at the end to force the robot to come to a "Holding" stop.
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(1000);  //wait 1 second for the robot to come to a complete stop.

}
