#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This program will use the VEX IQ Gyro sensor to display the three different types of values available
from the VEX IQ Gyro Sensor:
Degrees - The overall rotation value of the sensor in degrees. Can be positive or negative.
Heading - The current directional heading based on the last "reset". Returns a value of 0-359.
Rate    - The amount of the gyro changed in the last second. Can be positive or negative.

Note - Rotation to the Left of the gyro will increase the sensor's value
			 Rotation to the Right of the gyro will decrease the sensors value (the value can be negative)

Note: The VEX IQ Gyro Sensor returns values in degrees.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Info]
Port 7        			gyroSensor		      VEX IQ Distance		      		Gyro Sensor (returns degrees)
------------------------------------------------------------------------------------------------*/

task main()
{
	//Reset the gyro sensor to remove any previous data.
	resetGyro(gyroSensor);

	while(true)
	{
		//Display the 3 different values available from the Gyro Sensor
		displayTextLine(1, "Degrees: %d", getGyroDegrees(gyroSensor));
		displayTextLine(2, "Heading: %d", getGyroHeading(gyroSensor));
		displayTextLine(3, "   Rate: %d", getGyroRate(gyroSensor));
		sleep(50);  //Wait for 50ms to allow new data to be aquired.
	}
}
