#pragma config(StandardModel, "RVW RANGER")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Moving Forward
This program instructs your robot to move forward at full power for three seconds.
There is a two second pause at the beginning of the program.

Robot Model(s): TETRIX Ranger

[I/O Port]          [Name]              [Type]                		[Description]
mtr_S1_C1_1        rightMotor          TETRIX Motor             Right side motor
mtr_S1_C1_2        leftMotor           TETRIX Motor             Left side motor, reversed

----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at full power for 3 seconds
	motor[rightMotor] = 100;		  // Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = 100;		  // Motor on motorC is run at full (100) power forward
	wait1Msec(3000);			        // Robot runs previous code for 3000 milliseconds before moving on
}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
