#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Point Turns

This program instructs your robot to make a point turn right for 0.75 seconds, wait for 1 second and then
make a point turn left for 0.75 seconds.  There is a two second pause at the beginning of the program.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          NXT Motor             Right side motor
Motor Port 3        leftMotor           NXT Motor             Left side motor


----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Turn Right at full power for 0.75 seconds
	motor[rightMotor] = -100;		  // Motor on motorB is run at full (-100) power reverse
	motor[leftMotor]  = 100;			// Motor on motorC is run at full (100) power forward
	wait1Msec(750);					      // Robot runs previous code for 750 milliseconds before moving on

  motor[rightMotor] = 0;		    // Motor on motorB is turned off
	motor[leftMotor]  = 0;			  // Motor on motorC is turned off
	wait1Msec(1000);					    // Robot stops for 1 second

	// Turn Left at full power for 0.75 seconds
	motor[rightMotor] = 100;			// Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = -100;		  // Motor on motorC is run at full (-100) power reverse
	wait1Msec(750);					      // Robot runs previous code for 750 milliseconds before moving on
}													      // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
