#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	time1[T1] = 0;
	while (time1[T1] <= 600000)
	{
		getJoystickSettings(joystick);
		// Values of joysticks range from -127 to +127,
		// motors go from -100 to +100, so values need be scaled
		setMotorSpeed(leftMotor, (joystick.joy1_y1 * 100) / 127);
		setMotorSpeed(rightMotor, (joystick.joy1_y1 * 100) / 127);

		if (joy1Btn(Btn5))
		{
			setMotorSpeed(armMotor, 30);
		}
		else if (joy1Btn(Btn6))
		{
			setMotorSpeed(armMotor, -30);
		}
		else
		{
			setMotorSpeed(armMotor, 0);
		}
		sleep(100);
	}
}

