#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/********************************\
|*  ROBOTC Virtual World        *|
|*  encoders (Natural Language) *|
\********************************/

// This program drives forward for 2.0 rotations of the encoder, and then
// backward for 720 counts of the encoder.  (360 counts = 1.0 encoder)

task main()
{
  forward(75);                       		// move forward at speed 75
  untilRotations(2.0, leftEncoder);  		// continue until the left encoder reads 2.0 rotations (720 counts)
  stop();                            		// stop the robot

  wait(1.0);                         		// wait for 1 second

  backward(75);                      		// move backward at speed 75
  untilEncoderCounts(720, leftEncoder);		// continue until the left encoder reads 720 counts (2.0 rotations)
  stop();                            		// stop the robot
}
