#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************\
|*  ROBOTC Virtual World                            *|
|*  Move Straight for Rotations (Natural Language)  *|
\****************************************************/

// This program makes small corrections based on the values
// of the encoders to drive in a straight line for 5.0 rotations.

task main()
{
  moveStraightForRotations(5.0);    // drive straight forward for 5.0 rotations
  stop();                           // stop the robot
}
