#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************\
|*  ROBOTC Virtual World          *|
|*  Point Turn (Natural Language) *|
\**********************************/

// This program makes a sharp turn left for 1.5 seconds
// Followed by a sharp turn right for 1.5 seconds.

task main()
{
  pointTurn(left);    // make a sharp left turn
  wait(1.5);          // wait for 1.5 seconds
  stop();             // stop

  wait(1.0);          // wait for 1.0 seconds

  pointTurn(right);   // make a sharp right turn
  wait(1.5);          // wait for 1.5 seconds
  stop();             // stop
}
