#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************\
|*  ROBOTC Virtual World                *|
|*  sonar less than (Natural Language)  *|
\****************************************/

// This program moves forward until the sonar sensor sees an object less than 40 units away.

task main()
{
  forward(75);                // move forward at speed 75
  untilSonarLessThan(40);     // continue until the sonar reads a value less than 40
  stop();                     // stop the robot
}
