#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************\
|*  ROBOTC Virtual World          *|
|*  Swing Turn (Natural Language) *|
\**********************************/

// This program makes a wide turn left for 1.5 seconds
// Followed by a wide turn right for 1.5 seconds.

task main()
{
  swingTurn(left);    // make a wide left turn
  wait(1.5);          // wait for 1.5 seconds
  stop();             // stop

  wait(1.0);          // wait for 1.0 seconds

  swingTurn(right);   // make a wind right turn
  wait(1.5);          // wait for 1.5 seconds
  stop();             // stop
}
