#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/********************************\
|*  ROBOTC Virtual World        *|
|*  backward (Natural Language) *|
\********************************/

// This program drives backward at speed 75 for 2.5 seconds.

task main()
{
  backward(75);   // move backward at speed 75
  wait(2.5);      // wait for 2.5 seconds
  stop();         // stop the robot
}
