#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait(2);

  lineTrackForRotations(10, 2048, leftLineFollower, centerLineFollower, rightLineFollower);
  stop();

}
