#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************\
|*  ROBOTC Virtual World                      *|
|*  Move Straight for Time (Natural Language) *|
\**********************************************/

// This program makes small corrections based on the values
// of the encoders to drive in a straight line for 3.0 seconds.

task main()
{
  moveStraightForTime(3.0);   // drive straight forward for 3.0 seconds
  stop();                     // stop the robot
}
