#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		forward(360, degrees, 50);
		wait(2000, milliseconds);
		turnLeft(640, degrees, 50);
	}
}
