#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           gripperMotor,  tmotorVex269, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
2 Joystick Drive with Thresholds (Standard ROBOTC)
- This program allows you to remotely control your robot using the USB Logitech DualAction Joysticks.
- This program also ignores low values that would cause your robot to move when the joysticks fail to
	return back to exact center.  You may need to adjust the 'threshold' value to get it just right.
- For USB values to be transmitted to the robot, you must follow several steps:
- Use the "#include "JoystickDriver.c"" line at the beginning of your program
- Call the "getJoystickSettings(joystick);" in a loop to repeatedly retrieve the latest values
- Open the Robot > Debugger Windows > "Joystick Control - Basic" window after downloading your
	program to the virtual robot
	*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]               [Description]
Motor Port 1        gripperMotor        Motor        		     Front gripper motor
Motor Port 2        rightMotor          Motor        		     Right side motor
Motor Port 3        leftMotor           Motor          		   Left side motor
----------------------------------------------------------------------------------------------------*/

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

task main()
{
	//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
	//less than the threshold will be ignored.
	int threshold = 10;

	//Loop Forever
	while(1 == 1)
	{
		//Get the Latest joystick values
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y2) > threshold)     // If the right analog stick's Y-axis readings are either above or below the threshold...
		{
			motor[rightMotor] = joystick.joy1_y2;   // ...the right motor is assigned a power level equal to the right analog stick's Y-axis reading.
		}
		else                                      // Else the readings are within the threshold, so
		{
			motor[rightMotor] = 0;                  // ...the right motor is stopped with a power level of 0.
		}

		if(abs(joystick.joy1_y1) > threshold)     // If the left analog stick's Y-axis readings are either above or below the threshold...
		{
			motor[leftMotor] = joystick.joy1_y1;    // ...the left motor is assigned a power level equal to the left analog stick's Y-axis reading.
		}
		else                                      // Else if the readings are within the threshold...
		{
			motor[leftMotor] = 0;                   // ...the left motor is stopped with a power level of 0.
		}

		if(joy1Btn(6) == 1)       //If Button 6 is pressed...
		{
			motor[gripperMotor] = 63;     //...close the gripper.
		}
		else if(joy1Btn(8) == 1)  //Else, if button 8 is pressed...
		{
			motor[gripperMotor] = -63;     //...open the gripper.
		}
		else                      //Else (neither button is pressed)...
		{
			motor[gripperMotor] = 0;       //...stop the gripper.
		}
	}
}
