#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lineFollower,   sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          vacuumMotor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Crystal Path Insertion Point (Natural Language)
- This program will cause the robot to track the line from Sector 1 to the Unobtanium Cystal
	along Cystal Path, and activate the Vacuum attachment to absorb the Crystal.
- It will be up to you to deliver the Unobtanium Cystal by stopping the robot on the Cystal pad
	near the Rocket on the upper level.
- ROBOTC must be in Natural Language mode for this program to run. You can set this in the top menu
	by going to Robot > Platform Type > LEGO Mindstorms > Natural Language (NXT).
- Make sure that the VACUUM attachment is selected on the bottom of the Operation Reset window.
- Remember that you can press the "Reset" button in the lower-left corner of the Operation Reset
	window to return to the Insertion Point every time you modify your ROBOTC code.
*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]                   [Description]
Motor Port A        vacuumMotor        	Motor w/ Encoder       	 Front vacuum motor
Motor Port B        rightMotor          Motor w/ Encoder       	 Right side motor
Motor Port C        leftMotor           Motor w/ Encoder       	 Left side motor
Sensor Port 3				lightSensor					Line Following Sensor		 Sensor facing bottom center
----------------------------------------------------------------------------------------------------*/

//Every program has a task main(). All commands that the robot follows go between the curly braces.
task main()
{	//The program begins.
	wait(2.0);		//The robot will wait for 2 seconds before executing commands.

	//threshold is an integer variable that stores a value that is in between the white and black...
	//...line following values. It allows the robot to make decisions to track the line.
	int threshold = 25;

	//Track the line for 9 rotations of the motor encoders, up to the crystal.
	lineTrackLeft(lineFollower, threshold, 50, 0);
	waitUntil(nMotorEncoder[leftMotor] > (9 * 360));
	stopAllMotors();				//The robot stops.

	wait(1.0);		//The robot will wait for 1 second before executing other commands.

	turnRight(140, degrees, 50); //The robot turns left at power level 50, which is half power...
	                             //...until 140 degrees of the motor encoders have been detected.
															 // When it has reached 140 degrees, the robot will stop.

  wait(1.0);		//The robot will wait for 1 second before executing other commands.

  forward(0.75, rotations, 50); //The robot moves forward at power level 50, which is half power...
  	                            //...until 0.75 rotations of the motor encoders have been detected.
															  // When it has reached 140 degrees, the robot will stop.

	wait(1.0);		//The robot will wait for 1 second before executing other commands.

 	moveMotor(vacuumMotor, 1, seconds, -40); //The vacuummMotor is activated.
 																					 //Keep the vacuumMotor powered for 1 second.
 																					 //The crystal is absorbed, turn the vacuumMotor off.

}	//The program ends.
