#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
H2 Lift Road - Fueling the Rocket (Natural Language)
- This program will cause the robot to drive forward from Sector 1 to the Ion Propulsion Fuel Barrel
	near map intersection G3, pick it up, and turn toward the F3 Intraplanetary Boost Pad.
- It will be up to you to add the ROBOTC code that causes the robot to drive onto the Boost Pad,
	further into the zone, and then release the Fuel Barrel onto the Fuel Station.
- ROBOTC must be in Natural Language mode for this program to run. You can set this in the top menu
	by going to Robot > Platform Type > LEGO Mindstorms > Natural Language (NXT).
- Make sure that the GRIPPER attachment is selected on the bottom of the Operation Reset window.
- Remember that you can press the "Reset" button in the lower-left corner of the Operation Reset
	window to return to the Insertion Point every time you modify your ROBOTC code.
*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]                   [Description]
Motor Port A        gripperMotor        Motor w/ Encoder       	 Front gripper motor
Motor Port B        rightMotor          Motor w/ Encoder       	 Right side motor
Motor Port C        leftMotor           Motor w/ Encoder       	 Left side motor
----------------------------------------------------------------------------------------------------*/

//Every program has a task main(). All commands that the robot follows go between the curly braces.
task main()
{	//The program begins.
	wait(2.0);		//The robot will wait for 2 seconds before executing commands.

	forward(4.4, rotations, 50); //The robot moves forward at power level 50, which is half power...
															 //...until 4.4 rotations of the right motor encoder have been detected.
															 // When it has reached 3.5 rotations, the robot will stop.

	wait(1.0);		//The robot will wait for 1 second before executing other commands.


	turnRight(70, degrees, 50); //The robot turns left at power level 50, which is half power...
														  //...until a 70 degree turn of motor encoders have been detected.
  													  // When it has reached 70 degrees, the robot will stop.

 	wait(1.0);		//The robot will wait for 1 second before executing other commands.

 	moveMotor(gripperMotor, 1, seconds, 40); //Turn the gripperMotor on POSITIVE to CLOSE it around the Fuel Barrel.
 																					 //Give the gripperMotor 1 second to close...
 																					 //...before stopping the gripperMotor.

	wait(1.0);		//The robot will wait for 1 second before executing other commands.

	turnRight(60, degrees, 50); //The robot turns left at power level 50, which is half power...
														  //...until a 60 degree turn of motor encoders have been detected.
  													  // When it has reached 70 degrees, the robot will stop.

  //Enter the code for the robot to drive forward to the Interplanetary Boost Pad here:


  //Enter the code for the robot to drive forward to the Fuel Station here:


  //Enter the code for the robot to drop off the Fuel Barrel here:
  //Note: NEGATIVE motor power levels will OPEN the Gripper and release the Fuel Barrel!


}	//The program ends.
