#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lineFollower,   sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Sector 3 - Back Road Insertion Point (Natural Language)
- This program will cause the robot to drive forward from Sector 1 into Sector 3, and turn toward
	the Charge Cube in that area.
- It will be up to you to add the ROBOTC code that causes the robot to pick up the Charge Cube
	and take it to the Communication Tower pad.
- ROBOTC must be in Natural Language mode for this program to run. You can set this in the top menu
	by going to Robot > Platform Type > LEGO Mindstorms > Natural Language (NXT).
- Remember that you can press the "Reset" button in the lower-left corner of the Operation Reset
	window to return to the Insertion Point every time you modify your ROBOTC code.
*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]                   [Description]
Motor Port B        rightMotor          Motor        		    		 Right side motor
Motor Port C        leftMotor           Motor          		   	   Left side motor
----------------------------------------------------------------------------------------------------*/

//Every program has a task main(). All commands that the robot follows go between the curly braces.
task main()
{	//The program begins.
	wait(2.0);		//The robot will wait for 2 seconds before executing commands.

  forward(50, rotations, 50); // The robot moves forward at power level 50, which is half power...
  														// until 7 rotations on the encoders have been detected.
  														// The robot will come to a stop after it has completed this.

	wait(1.0);		//The robot will wait for 1 second before executing other commands.

	turnLeft(60, degrees, 50); // The robot turns left at power level 50, which is half power...
  												   // until 60 counts of the right motor encoder have been detected.
														 // The robot will come to a stop after it has completed this.

  //Enter the code for the robot to drive forward to the charge cube here:


  //Enter the code for the robot to turn right toward the Communication Tower here:


  //Enter the code for the robot to drive forward to the Communication Tower pad here:


}	//The program ends.
