#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lineFollower,   sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Sector 2 - West Road Insertion Point (Natural Language)
- This program will cause the robot pick up the Charge Cube along West Road using feedback from
	the Sonar Sensor.
- It will be up to you to deliver the Charge Cube to the Communication Tower Pad in Sector 2.
- ROBOTC must be in Natural Language mode for this program to run. You can set this in the top menu
	by going to Robot > Platform Type > LEGO Mindstorms > Natural Language (NXT).
- Remember that you can press the "Reset" button in the lower-left corner of the Operation Reset
	window to return to the Insertion Point every time you modify your ROBOTC code.
*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]                   [Description]
Motor Port A        gripperMotor        Motor        		    		 Front gripper motor
Motor Port B        rightMotor          Motor w/ Encoder       	 Right side motor
Motor Port C        leftMotor           Motor w/ Encoder       	 Left side motor
Sensor Port 4				sonarSensor					Sonar Sensor						 Sensor facing front center
----------------------------------------------------------------------------------------------------*/

//Every program has a task main(). All commands that the robot follows go between the curly braces.
task main()
{	//The program begins.
	wait(2.0);		//The robot will wait for 2 seconds before executing commands.

  forward(50);	//The robot moves forward at power level 50, which is half power...
  waitUntil(SensorValue[sonarSensor] < 20); //...until the Sonar Sensor detects it is within 20 cm of the wall.
	stopAllMotors();				//The robot stops.

	//Enter the code for the robot to turn toward Sector 2 here:


	//Enter the code for the robot to drive forward into Sector 2 here:


	//Enter the code for the robot to turn toward the Communication Tower pad here:


	//Enter the code for the robot to drive to the Communication Tower pad here:


}	//The program ends.
