#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
The VEX IQ Distance sensor is able to detect objects up to 600mm (60cm) away by default. This range
is the optimal range for the Distance Sensor, but the distance sensor is able to detect up to 1000mm.
You can also change the minimum range to ignore objects that are too close (like a lifter arm).
This program will switch the range of the sensor by adjusting both the minimum and maximum detected
range for the sensor.

Note: The VEX IQ Distance Sensor returns values in millimeters.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Info]
Port 7        			distanceSensor      VEX IQ Distance		      		Distance Sensor (returns mm)
Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
int minRange = 0;
int maxRange = 0;


task main()
{
 	//Set the minimum detectable range to 200mm (20cm)
	setDistanceMinRange(distanceMM, 200);

  //Set the maximum detectable range to 1000mm (100cm/1.00m)
	setDistanceMaxRange(distanceMM, 1000);

	while(true)
	{
		//Display the 3 different values from the Distance Sensor to the VEX IQ LCD Screen
		displayTextLine(1, "Distance: %d mm", getDistanceValue(distanceMM));
		sleep(50);  //Delay 50ms to allow new data to appear.
	}
}
