#pragma config(Sensor, port7, distanceSensor,     sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

TDistanceInfo nInfo;
unsigned int MinDistance = 250;  //In MM
unsigned int MaxDistance = 1000; //In MM
unsigned int SNRThresh = 0;  //in SNR Values
unsigned int BrightnessThresh = 0; //in SNR Values
unsigned int FilterFact = 1; //0-7
unsigned int TransmitPower = 1;  //Non Zero - On , Zero - Off

task main()
{
	while(true)
	{
		setDistanceMinRange(distanceSensor, MinDistance);
		setDistanceMaxRange(distanceSensor, MaxDistance);
		setDistanceSNRThreshold(distanceSensor, SNRThresh);
		setDistanceBrightnessThreshold(distanceSensor, BrightnessThresh);
		setDistanceFilterFactor(distanceSensor, FilterFact);
		setDistanceTransmitPower(distanceSensor, TransmitPower);
		getDistanceAdvanced(distanceSensor, nInfo);

		wait1Msec(50);
	}
}
