#pragma config(Sensor, S1,     nCompass,       sensorI2CHiTechnicCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform (NXT, TETRIX)
#pragma fileExtension("rtm")

#include "AdvancedSensors.c"    // include library files

task main()
{
	int nCompassHeading;
	int nLastX     = 31; // out of range to force initial display
	int nLastY     = 31; // out of range to force initial display

	displayCenteredBigTextLine(0, "Compass");
	displayCenteredBigTextLine(2, "Test");

  displayCenteredTextLine(5, "Connect Compass");
  displayCenteredTextLine(6, "to any port");

  nCompassHeading = SensorValue[nCompass];
	wait1Msec(10);

	//
	// Clear screen and setup variables
	//
	eraseDisplay();
	//
	// Repeat forever display angle and sine on the NXT LCD display
	//
  drawEllipse(0, 62, 62, 0);
	displayStringAt(29, 58, "N");
	displayStringAt(29,  8, "S");
	displayStringAt( 3, 34, "W");
	displayStringAt(54, 34, "E");
  drawLine(31, 31, nLastX, nLastY);
  while (true)
	{
		int X;
		int Y;

	  //
	  // Normalize
	  //
	  nCompassHeading = SensorValue[nCompass] % 360;
	  if (nCompassHeading < 0)
	    nCompassHeading += 360;

    X = 31 + (float) (sinDegrees(nCompassHeading) * 31);
    Y = 31 + (float) (cosDegrees(nCompassHeading) * 31);
	  if ((nLastX != X)  || (nLastY != Y))
	  {
	  	//
	  	// Position has changed. Redraw some screen elements
	  	// If unchanged, skip to avoid screen flicker
	  	//
		  invertLine(31, 31, X,  Y);
		  invertLine(31, 31, nLastX, nLastY);
			//invertLine(31, 31, nLastLastX, nLastLastX);

		  //
		  // Numeric display of 'compass on right of screen
		  //
		  displayStringAt(57, 60, "Heading");
		  displayStringAt(65, 52, "%+5d", nCompassHeading);

		  displayStringAt(75, 16, "Port");
		  displayStringAt(80,  8, "S%1d", (short) ((short) nCompass + 1));

		  nLastX = X;
		  nLastY = Y;
		}

  }
  return;
}
