#pragma config(Sensor, S2,     sound,               sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                       "Try Me" Program for NXT Sound Sensor
//
///////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma fileExtension("rtm")
#pragma platform("NXT")

void displaySensorValue()
{
	//
	// DIsplay the sound sensor value. But we'll filter it to avoid "noise"
	//
	static int nLastDisplayedValue = 0;
	static int nDiffValueCount = 0;
	int nCurrValue;
	int nDiff;

	nCurrValue = SensorValue[sound];
	nDiff = nLastDisplayedValue - nCurrValue;
	nDiff = abs(nDiff);
	if (nDiff != 0)
	{
		//
		// Value has changed. If its a small change, then we need 10 consecutive changed
		// value before the display is updated.
		//
		// If it is a big change (i.e. more than 2) then display it right away.
		//
		if (nDiff <= 2)
		{
			nDiffValueCount++;//increment the value by 1. same as nDiffValueCount=nDiffValueCount+1;
			if (nDiffValueCount < 10)
				return;//Terminates function early because the change could be noise
		}
	}
	else
	{
		nDiffValueCount = 0;
		return;//Terminates function early because the sound data hasn't changed so the display doesn't need updating
	}

	//
	// Display the sound level using the large font
	//
	displayCenteredBigTextLine(6, "%d", nCurrValue);
	nLastDisplayedValue = nCurrValue;
	nDiffValueCount = 0;
	return;
}

task main()
{
	//
	// Grab LCD screen and initialize display
	//
	displayCenteredBigTextLine(0, "Sound");
	displayCenteredBigTextLine(2, "Test");
	displayCenteredTextLine(4, "Connect Sensor");
	displayCenteredTextLine(5, "to Port S2");

	wait1Msec(500);
	displayCenteredTextLine(4, "Port S2");
	displayCenteredTextLine(5, "Sound Level");

	while (true)
	{
		displaySensorValue();
		motor[motorB] = +SensorValue[sound];
		motor[motorC] = -SensorValue[sound];
		wait1Msec(5);
	}
}
