#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		if (getBumperValue(bumpSwitch) == 1) {
			setMotorTarget(armMotor, 360, 50);
		} else {
			setMotorTarget(armMotor, 0, 50);
		}
	}
}
