#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	setMultipleMotors(50, leftMotor, rightMotor, rightMotor, rightMotor);
	wait(3, seconds);
	stopAllMotors();
}
