#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Top Hat Drive
- This program allows you to remotely control your robot using the "Top Hat" on the
  USB Logitech Dual Action controller.
- For USB values to be transmitted to the robot, you must follow several steps:
  - Use the "#include "JoystickDriver.c"" line at the beginning of your program
  - Call the "getJoystickSettings(joystick);" in a loop to repeatedly retrieve the latest values
  - Open the Robot > Debugger Windows > "Joystick Control - Basic" window after downloading your
    program to the virtual robot

Robot Model(s): Squarebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          VEX Motor             Right side motor
Motor Port 3        leftMotor           VEX Motor             Left side motor

*To run this sample program on Swervebot, be sure to Reverse Motor Port 3 in the Motors and Sensors
 Setup, and to make sure that Motor Port 2 is NOT Reversed.
----------------------------------------------------------------------------------------------------*/

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

task main()
{
  //Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
  //less than the threshold will be ignored.
  int threshold = 10;

  //Loop Forever
  while(1 == 1)
  {
    //Get the Latest joystick values
    getJoystickSettings(joystick);

    //If the top side is pressed...
    if(joystick.joy1_TopHat == 0)
    {
      //...move forward.
      motor[rightMotor] = 60;
      motor[leftMotor] = 60;
    }
    //Else, if the bottom side is pressed...
    else if(joystick.joy1_TopHat == 4)
    {
      //...move in reverse.
      motor[rightMotor] = -60;
      motor[leftMotor] = -60;
    }
    //Else, if the right side is pressed...
    else if(joystick.joy1_TopHat == 2)
    {
      //...turn right.
      motor[rightMotor] = -63;
      motor[leftMotor] = 63;
    }
    //Else, if the left side is pressed..
    else if(joystick.joy1_TopHat == 6)
    {
      //...turn left
      motor[rightMotor] = 63;
      motor[leftMotor] = -63;
    }
    //Else (nothing pressed)...
    else
    {
      //...stop.
      motor[rightMotor] = 0;
      motor[leftMotor] = 0;
    }

  }
}
