#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		tankControl(ChD, ChA, 10);
		if (getJoystickValue(BtnEUp) == 1) {
			forward(1.5, rotations, 50);
		}
		if (getJoystickValue(ChD) == 1) {
			backward(.75, rotations, 50);
		}
	}
}
