#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetTimer(T1);
	repeatUntil (getTimer(T1, seconds) > 30) {
		arcadeControl(ChA, ChB, 10);
	}
}
