#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetTimer(T1);
	repeatUntil (getTimer(T1, milliseconds) >= 60000) {
		tankControl(JoyY2, JoyY1, 10);
		armControl(motorA, Btn5, Btn6, 75);
	}
}
