#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetTimer(T1);
	while (getTimer(T1, seconds) < 5) {
		setMotor(motor1, 50);
		setMotor(motor6, 50);
	}
}
