#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Modifying Values

This program instructs your robot to move forward at half power for 1.5 seconds, brake for 1
second, reverse for 1.5 seconds, and turn left for 0.75 seconds.  There is a two second pause at
the beginning of the program.

Robot Model(s): Squarebot & Swervebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          VEX Motor             Right side motor
Motor Port 3        leftMotor           VEX Motor             Left side motor

*To run this sample program on Swervebot, be sure to Reverse Motor Port 3 in the Motors and Sensors
 Setup, and to make sure that Motor Port 2 is NOT Reversed.
----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						  // Robot waits for 2000 milliseconds before executing program

	// Move forward at half power for 1.5 seconds
	motor[rightMotor] = 63;			  // Motor on port2 is run at half (63) power forward
	motor[leftMotor]  = 63;			  // Motor on port3 is run at half (63) power forward
	wait1Msec(1500);				      // Robot runs previous code for 1500 milliseconds before moving on

	// Brake for 1 second
	motor[rightMotor] = 0;				// Motor on port2 is stopped
	motor[leftMotor]  = 0;				// Motor on port3 is stopped
	wait1Msec(1000);				      // Robot runs previous code for 1000 milliseconds before moving on

	// Move reverse at half power for 1.5 seconds
	motor[rightMotor] = -63;			// Motor on port2 is run at half (63) power reverse
	motor[leftMotor]  = -63;			// Motor on port3 is run at half (63) power reverse
	wait1Msec(1500);				      // Robot runs previous code for 1500 milliseconds before moving on

	// Turn left at full power for 0.75 seconds
	motor[rightMotor] = 127;			// Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = -127;		  // Motor on port3 is run at full (-127) power reverse
	wait1Msec(750);					      // Robot runs previous code for 750 milliseconds before moving on
}													      // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
