#pragma config(Sensor, port2,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  Simple program to make your robot move forward until the Bumper Sensor is triggered (pressed).

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
    Port 2        			bumpSwitch          VEX IQ Bumper		      			Bumper Sensor
------------------------------------------------------------------------------------------------*/

task main()
{
	while(getBumperValue(bumpSwitch) == 0)	// Loop while robot's bumper/touch sensor isn't pressed in
	{
		setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
		setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	}
	//Once the sensor is touched, the program will end and motors will stop.
}
