#pragma config(Sensor, port2,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
	This program instructs the robot to move forward at half speed until the bumper sensor is
	released.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
    Port 2        			bumpSwitch          VEX IQ Bumper		      			Bumper Sensor
------------------------------------------------------------------------------------------------*/

task main()
{
	while(getBumperValue(bumpSwitch) == 0)	// Instructs robot to do nothing while the touch sensor isn't pressed
	{
		//Idle Loop - Will continuously check the while loop's condition
	}

	while(getBumperValue(bumpSwitch) == 1)	// Loop while robot's bumper/touch sensor IS pressed in
	{
		setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
		setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
