#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program uses the DisplayTextLine function of ROBTOC on the VEX IQ Platform.
	It will display a message and a number.


                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)

------------------------------------------------------------------------------------------------*/

task main()
{
	int displayValue = 250;

  displayTextLine(1, "Hello from");   // Display "Hello from"
  displayTextLine(2, "ROBOTC  :]");   // Display "ROBOTC :]"
  displayTextLine(3, "My Value is: %d", displayValue); //Display a number to the screen.

  while(true)                           // An infinite loop to keep the program running until you terminate it
  {
  	sleep(10);
  }
}
