#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motorA,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorB,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorC,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_1, motorD,        tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorNone, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		int nSpeed;
		for (nSpeed = -100; nSpeed <= 100; nSpeed += 10)
		{
			motor[motorD] = nSpeed;
			motor[motorE] = -nSpeed;
			servo[servo1] = 100 + nSpeed;
			servo[servo2] = 100 + nSpeed;
			servo[servo3] = 100 + nSpeed;
			servo[servo4] = 100 + nSpeed;
			wait1Msec(1000);
		}
		for (; nSpeed > -100; nSpeed -= 10)
		{
			motor[motorD] = nSpeed;
			motor[motorE] = -nSpeed;
			servo[servo1] = 100 + nSpeed;
			servo[servo2] = 100 + nSpeed;
			servo[servo3] = 100 + nSpeed;
			servo[servo4] = 100 + nSpeed;
			wait1Msec(1000);
		}
	}
}
