#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intakeMotor,   tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
This program is designed to give new programmers beginning code that allows their robots to move from
point to point on the gameboard. The program uses three functions: moveForward, turnRight, and turnLeft
to move around the gameboard.  Each of the functions accepts two paramenters: encoderCounts and speed.

Conveyorbot - Basic Movement
- This program demonstrates basic movements (forward, turn left, turn right) that can be performed
with the Conveyorbot using encoder-based programming.

Robot Model(s): TETRIX Conveyorbot (Virtual Worlds)
[I/O Port]          [Name]              [Type]                [Description]
Motor Port D        rightMotor          TETRIX Motor          Right side motor
Motor Port E				leftMotor						TETRIX Motor					Left side motor
Motor Port F 				armMotor						TETRIX Motor					Arm motor
Motor Port G 				intakeMotor					TETRIX Motor 					Intake motor

Sensor Port 2				gyro								HiTechnic Gyro				HiTechnic Gyro
Sensor Port 3				light   						Light Sensor					NXT Light Sensor (Active)
Sensor Port 4				sonar 							Sonar Sensor					NXT Sonar Sensor
----------------------------------------------------------------------------------------------------*/

//Function to move the robot forward for a specified amount of encoder counts
//at a specified speed
void moveForward(int encoderCounts, int speed)
{
	//Clear the encoders before using them
	nMotorEncoder(rightMotor) = 0;
	nMotorEncoder(leftMotor)  = 0;

	//While both of the encoders are less than the specified amount
	while(nMotorEncoder(rightMotor) < encoderCounts && nMotorEncoder(leftMotor) < encoderCounts)
	{
		//If both of the encoder values are equal
		if (nMotorEncoder(rightMotor) == nMotorEncoder(leftMotor))
		{
			//Move the robot forward at the specified speed
			motor[rightMotor]  = speed;
			motor[leftMotor]   = speed;

		}

		//If the right encoder is greater than the left encoder (veering left)
		else if (nMotorEncoder(rightMotor) > nMotorEncoder(leftMotor))
		{
			//Adjust the robot to the right
			motor[rightMotor]  = speed;
			motor[leftMotor]   = speed+5;
		}

		//If the left encoder is greater than the right encoder (veering right)
		else if (nMotorEncoder(rightMotor) < nMotorEncoder(leftMotor))
		{
			//Adjust the robot to the left
			motor[rightMotor]  = speed+5;
			motor[leftMotor]   = speed;
		}
	}

	//Stop the robot
	motor[rightMotor]  = 0;
	motor[leftMotor]   = 0;

}

//Turn the robot left for the specified encoder counts
//at a specified speed
void turnLeft(int encoderCounts, int speed)
{
	//Clear the encoders before using them
	nMotorEncoder(rightMotor) = 0;
	nMotorEncoder(leftMotor)  = 0;

	//While the absolute value of the right motor's encoder is less
	//than the specified amount
	while(abs(nMotorEncoder(rightMotor)) < encoderCounts)
	{
		//Turn the robot to the left at the specified speed
		motor[rightMotor]  = speed;
		motor[leftMotor]   = -speed;

	}

	//Stop the robot
	motor[rightMotor]  = 0;
	motor[leftMotor]   = 0;

}

//Turn the robot left for the specified encoder counts
//at a specified speed
void turnRight(int encoderCounts, int speed)
{
	//Clear the encoders
	nMotorEncoder(rightMotor) = 0;
	nMotorEncoder(leftMotor)  = 0;

	//While the absolute value of the left motor's encoder is less
	//than the specified amount
	while(abs(nMotorEncoder(leftMotor)) < encoderCounts)
	{
		//Turn the robot to the right at the specified speed
		motor[rightMotor]  = -speed;
		motor[leftMotor]   = speed;

	}

	//Stop the robot
	motor[rightMotor]  = 0;
	motor[leftMotor]   = 0;

}

task main()
{
	//Move the robot forward for 1000 encoder counts
	//at a speed of 50, then wait for half of a second
	moveForward(1000, 50);
	wait1Msec(500);

	//Turn the robot to the right for 1290 encoder counts
	//at a speed of 25, then wait for half of a second
	turnRight(1290, 25);
	wait1Msec(500);

	//Turn the robot to the left for 1290 encoder counts
	//at a speed of 25, then wait for half of a second
	turnLeft(1290, 25);
	wait1Msec(500);
}
