#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  int threshold = 65;

  while(getUSDistance(sonarSensor) >= 20)
  {
    // sensor sees light:
    if(getColorReflected(colorSensor) < threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = 15;
      motor[rightMotor] = 55;

    }
    // sensor sees dark:
    else
    {
      // counter-steer left:
      motor[leftMotor]  = 55;
      motor[rightMotor] = 15;
    }
  }
}
