#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	waitUntil (getTouchLEDValue(touchLED) == 1);
	forward(2.5, rotations, 50);
	turnLeft(230, degrees, 50);
	backward(1.5, rotations, 50);
}
