#pragma config(Sensor, port5,  colorDetector,  sensorVexIQ_ColorHue)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  A basic loop to detect a range of hue values. The VEX IQ Color sensor returns hue as a 0-255 value.
  This is different than normal "hue" readings which range from 0-359.

  This program will use the following ranges to print on the LCD screen the current color it sees:
  Red: 0 to 50 / 220 to 255
  Green: 51 to 130
  Blue 131 to 219

  Using "else if" and the "&&" (Logical AND), we can make ranges of values to detect different colors/conditions.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 5       				colorDetector       VEX IQ Color		      			Color Detector (Hue Color Mode)
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		if(getColorValue(colorDetector) < 50)
		{
			//Detect a Red Color
			displayTextLine(1, "I see RED!");  //Command to Write to the LCD Screen
		}
		else if((getColorValue(colorDetector) > 50) && (getColorValue(colorDetector) <= 130))
		{
			//Detect a Green Color
			displayTextLine(1, "I see GREEN!");  //Command to Write to the LCD Screen
		}
		else if((getColorValue(colorDetector) > 131) && (getColorValue(colorDetector) <= 219))
		{
			//Detect a Blue Color
			displayTextLine(1, "I see BLUE!");  //Command to Write to the LCD Screen
		}
		else if(getColorValue(colorDetector) > 219)
		{
			//Detect a Red Color (second half of the range)
			displayTextLine(1, "I see RED!");  //Command to Write to the LCD Screen
		}

		sleep(25); //Small delay to allow color sensor to detect any changes in color
	}
}
