#pragma config(Sensor, port5,  colorDetector,  sensorVexIQ_Color12Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
The color sensor also has a "proximity" detection ability that will allow you to know if color sensor
is far or close to the object it is currently detecting.

The "proximity" values range from 0-1023, but expect values to be between 100-500,
with higher values being "closer" to an object. To assist with debugging,
this program will print the proximity value to the screen.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Location]
Port 5       				colorDetector       VEX IQ Color		      			Color Detector (Hue Color Mode)
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		// Display value of the color on the LCD screen.
		if(getColorName(colorDetector) == colorRed)  		 //Color #1
		{
			displayTextLine(1, "Red Colored Object");
		}
		else if(getColorName(colorDetector) == colorBlue)  //Color #2
		{
			displayTextLine(1, "Blue Colored Object");
		}
		else if(getColorName(colorDetector) == colorGreen)  //Color #3
		{
			displayTextLine(1, "Green Colored Object");
		}
		else
		{
			displayTextLine(1, "Some Other Color");
		}

		//Set your color proximity threshold to say if we're close or far away from an object.
		//To learn what values you get, we'll also print the proximity value to the LCD screen.
		if(getColorProximity(colorDetector) > 200)
		{
			displayTextLine(2, "Detected Close");
			displayTextLine(3, "Proximity Value: %d", getColorProximity(colorDetector));
		}
		else
		{
			displayTextLine(2, "Detected Far Away");
			displayTextLine(3, "Proximity Value: %d", getColorProximity(colorDetector));
		}

		sleep(100);
	}
}
