#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	forward(5, rotations, 100);
	stopAllMotors();
	wait(1, seconds);
	backward(5, rotations, 100);
	stopAllMotors();
	wait(1, seconds);
	turnLeft(180, degrees, 50);
	stopAllMotors();
	wait(1, seconds);
	turnRight(180, degrees, 50);
}
