#pragma config(Sensor, S4,     sonarSensor,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                      Bad Sonar Tracking Program                                        *|
|*                                                                                                        *|
|*  Not only is this code a poor example of controling your robot with sonar (it is too jerky and will    *|
|*  probably shake your robot apart!) but it is also written in very poor style.  Avoid making your       *|
|*  programs small and confusing.  Take time to expand your program, try to only do one 'thing' per line. *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.                 *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
|*    Port 4                  sonarSensor         Sonar Sensor        Front mounted, front facing         *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main(){
  int speed = 0;                            // Will hold the speed of the motors.

  for(;;){                                  // 'for ever'
    if(SensorValue(sonarSensor) > 35)                      // '> 35' tells the robot to go forward while the Sonar Sensor reads in data greater than 35cm away.
      motor[motorC] = motor[motorB] = speed = 100;                  // Read from Right to Left: '100 is assigned speed is assigned to motorE is assigned to motorD'.
    else if(SensorValue(sonarSensor) < 35)                  // If the object is closer than 35cm...
      motor[motorC] = motor[motorB] = speed = -100;                 // Back up FULL SPEED! (to avoid collision #_# )
    else                                                    // If the object is exactly 35cm away...
      motor[motorC] = motor[motorB] = speed = 0;                    // STOP!  Goal reached.

      displayCenteredTextLine(0, "Sonar Reading");                     /* Display Sonar Sensor values */
      displayCenteredBigTextLine(2, "%d", SensorValue(sonarSensor));   /* to LCD screen using %d.     */

      displayCenteredTextLine(5, "%d", speed);                         /* Display variable 'speed' to the LCD.       */
      displayCenteredTextLine(7, "Motor Speed");                       /* (which is the current speed of the motors) */
  }
}
