#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(rightMotor, 50);
	setMotorSpeed(leftMotor, 50);
	while(true)
	{
		if (getUSDistance(sonarSensor) < 20)
		{
			moveMotorTarget(leftMotor, -720, 50);
			moveMotorTarget(rightMotor, -720, 50);
			while(getMotorRunning(leftMotor) || getMotorRunning(rightMotor))
			{
				sleep(1);
			}
		}
	}
}
