#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Use Global Variables to monitor the state of the motor
bool overTemp;
bool currentLimitFlag;
bool zeroVelocity;
bool zeroPosition;
TMotorBrakeModes currentBrakeMode;
int currentMotorStrength;

task main()
{
	moveMotorTarget(rightMotor, 2000, 50);

	while(true)
	{
		//Boolean Flag to report if the motor is overheating.
		overTemp							= getMotorOverTemp(rightMotor);

		//Boolean Flag to report if the motor has exceed it's current (strength) limit.
		currentLimitFlag			= getMotorCurrentLimitFlag(rightMotor);

		//Boolean Flag to report if the motor's velocity is zero.
		//You can use this to detect if a "setMotorPosition" command is complete.
 		zeroVelocity					= getMotorZeroVelocity(rightMotor);

 		//Boolean Flag to report if the motor's encoder is within +/- 3 counts of it's requested "position".
 		zeroPosition					= getMotorZeroPosition(rightMotor);

 		//Retrieves the current "Brake Mode" - Either Coast, Brake or Hold
		currentBrakeMode			= getMotorBrakeMode(rightMotor);

		//Gets the current (strength) limit of the motor on a scale of 0-255. The programmable fuse is set
		//with a value of approx 15mA per "count" (i.e. a count of 66 = 1Amp fuse)
		currentMotorStrength  = getMotorStrength(rightMotor);
		sleep(10);
	}
}
