#pragma config(StandardModel, "VEX IQ Clawbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will cycle through and test the different motor "Braking" modes that are available
  with the VEX IQ motors. The VEX IQ motors support 3 different "braking" modes:

  motorCoast -> Coasting: Motor is completely unpowered and easy to move by hand.
  motorBrake -> Brake: Motor is electrically braked and will resist some movement.
  motorHold -> Holding: Motor is programmatically braked and resisting movement with force. The motor
  											will automatically return to its position if moved forcefully.

  These modes only apply when setting the speed/power level to zero. Motors will always be in
  "Hold" mode after a "setMotorPosition" or "setServoPosition" command.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)

------------------------------------------------------------------------------------------------*/

task main()
{
	//************* Brake Mode *********************//

	//Turn motors on and set brake mode to "Brake"
	setMotorSpeed(leftMotor, 75);
	setMotorSpeed(rightMotor, 75);
	setMotorBrakeMode(leftMotor, motorBrake);
	setMotorBrakeMode(rightMotor, motorBrake);
	sleep(1000);

	//Stop motor for 5 seconds - try to move the motor by hand at this time.
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(5000);

	//************* Coast Mode *********************//

	//Turn motors on and set brake mode to "Coast"
	setMotorSpeed(leftMotor, 75);
	setMotorSpeed(rightMotor, 75);
	setMotorBrakeMode(leftMotor, motorCoast);
	setMotorBrakeMode(rightMotor, motorCoast);
	sleep(1000);

	//Stop motor for 5 seconds - try to move the motor by hand at this time.
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(5000);

	//************* Hold Mode *********************//

	//Turn motors on and set brake mode to "Hold"
	setMotorSpeed(leftMotor, 75);
	setMotorSpeed(rightMotor, 75);
	setMotorBrakeMode(leftMotor, motorHold);
	setMotorBrakeMode(rightMotor, motorHold);
	sleep(1000);

	//Stop motor for 5 seconds - try to move the motor by hand at this time.
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(5000);
}
