#pragma config(StandardModel, "RVW RANGER")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Point Turns with Encoders

This program instructs the robot to turn left, and then right, using feedback from the encoders.
There is a two second pause at the beginning of the program.

The used for feedback should be cleared just before it starts counting  using the
"nMotorEncoder(encoder) = 0;".  This helps ensure consistancy.

Robot Model(s): TETRIX Ranger

[I/O Port]          [Name]              [Type]                		[Description]
mtr_S1_C1_1        rightMotor          TETRIX Motor             Right side motor
mtr_S1_C1_2        leftMotor           TETRIX Motor             Left side motor, reversed

----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);							            //Robot waits for 2000 milliseconds before executing program

	nMotorEncoder[rightMotor] = 0;	          //Set the encoder so that it starts counting at 0

  while(nMotorEncoder(rightMotor) < 1800)   //While rightEncoder has counted less than 1800 counts
	{
		//Turn Left
		motor[rightMotor] = 100;					      //Motor on motorB is run at full (100) power forward
		motor[leftMotor]  = -100;				        //Motor on motorC is run at full (-100) power reverse
	}

	nMotorEncoder[leftMotor] = 0;	            //Set the encoder so that it starts counting at 0

  while(nMotorEncoder(leftMotor) < 1800)    //While leftEncoder has counted less than 1800 counts
	{
		//Turn Right
		motor[rightMotor] = -100;				        //Motor on motorB is run at full (-100) power reverse
		motor[leftMotor]  = 100;				      	//Motor on motorC is run at full (100) power forward
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
