#pragma config(Sensor, port12,  touchLED,      sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will cycle through the three primary colors of the Touch LED sensor (Red/Green/Blue)
  Each LED Color has a range between 0-255, determining the brightness of that individual color.

  To turn off the Touch LED, set all 3 color values to zero.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    port 12							touchLED						VEX IQ Touch LED						Detect Touches and Set Colors
------------------------------------------------------------------------------------------------*/

task main()
{
	//Phase 1 - Test all 3 colors
	clearTimer(T1);

	while(time1[T1] < 5000)
	{
		setTouchLEDRGB(touchLED, 255, 0, 0);
		sleep(100);
		setTouchLEDRGB(touchLED, 0, 255, 0);
		sleep(100);
		setTouchLEDRGB(touchLED,	0, 0, 255);
		sleep(100);
	}
}
