#pragma config(Sensor, port12,  touchLED,      sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  Enabled the "fade between colors" feature of the Touch LED. This allows the Touch LED to smoothly
  fade between two colors. Note that the Touch LED must already be on before setting a "fade" setting
  or the Touch LED sensor may not respond to future color settings.

  Valid "Fade" settings:
  colorFadeNone / colorFade72ms /	colorFade170ms / colorFade370ms / colorFade770ms /
	colorFade1570ms / colorFade3240ms / colorFade6480ms / colorFade13sec / colorFade26sec

	Setting the "Fade" setting to "colorFadeNone" will disable the fade feature.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    port 12							touchLED						VEX IQ Touch LED						Detect Touches and Set Colors
------------------------------------------------------------------------------------------------*/

task main()
{
	//Start Up Color - Turns the TouchLED On
	setTouchLEDRGB(touchLED, 255, 255, 255);
	sleep(1000);

	//Enable Fade Mode - Will fade for 770ms between colors.
	setTouchLEDFade(touchLED, colorFade770ms);

	while(true) //Cycle between two colors - notice the fade!
	{
		setTouchLEDRGB(touchLED, 0, 255, 0);
		sleep(2000);
		setTouchLEDRGB(touchLED, 0, 0, 255);
		sleep(2000);
	}
}
